##########################################################################
# Title:            Sandbox: gaps | Default Variables                    #
# Author(s):        JigSawFr                                             #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

gaps_name: gaps

################################
# Paths
################################

gaps_role_paths_folder: "{{ gaps_name }}"
gaps_role_paths_location: "{{ server_appdata_path }}/{{ gaps_role_paths_folder }}"
gaps_role_paths_folders_list:
  - "{{ gaps_role_paths_location }}"

################################
# Web
################################

gaps_role_web_subdomain: "{{ gaps_name }}"
gaps_role_web_domain: "{{ user.domain }}"
gaps_role_web_port: "8484"
gaps_role_web_url: "{{ 'https://' + (gaps_role_web_subdomain + '.' + gaps_role_web_domain
               if (gaps_role_web_subdomain | length > 0)
               else gaps_role_web_domain) }}"

################################
# DNS
################################

gaps_role_dns_record: "{{ gaps_role_web_subdomain }}"
gaps_role_dns_zone: "{{ gaps_role_web_domain }}"
gaps_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

gaps_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
gaps_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
gaps_role_traefik_middleware_custom: ""
gaps_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
gaps_role_traefik_enabled: true
gaps_role_traefik_api_enabled: false
gaps_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
gaps_role_docker_container: "{{ gaps_name }}"

# Image
gaps_role_docker_image_pull: true
gaps_role_docker_image_tag: "latest"
gaps_role_docker_image: "housewrecker/gaps:{{ gaps_role_docker_image_tag }}"

# Envs
gaps_role_docker_envs_default:
  TZ: "{{ tz }}"
  # BASE_URL: "{{ gaps_role_web_url }}"
  ENABLE_LOGIN: "false"
  ENABLE_SSL: "false"
gaps_role_docker_envs_custom: {}
gaps_role_docker_envs: "{{ gaps_role_docker_envs_default
                      | combine(gaps_role_docker_envs_custom) }}"

# Volumes
gaps_role_docker_volumes_default:
  - "{{ gaps_role_paths_location }}:/usr/data"
gaps_role_docker_volumes_custom: []
gaps_role_docker_volumes: "{{ gaps_role_docker_volumes_default
                         + gaps_role_docker_volumes_custom }}"

# Hostname
gaps_role_docker_hostname: "{{ gaps_name }}"

# Networks
gaps_role_docker_networks_alias: "{{ gaps_name }}"
gaps_role_docker_networks_default: []
gaps_role_docker_networks_custom: []
gaps_role_docker_networks: "{{ docker_networks_common
                          + gaps_role_docker_networks_default
                          + gaps_role_docker_networks_custom }}"

# Restart Policy
gaps_role_docker_restart_policy: unless-stopped

# State
gaps_role_docker_state: started
