##########################################################################
# Title:         Sandbox: vnstat | Default Variables                     #
# Author(s):     turbo                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

vnstat_name: vnstat

################################
# Settings
################################

vnstat_page_refresh: "0"
vnstat_rate_unit: "1" # Used traffic rate unit, 0: bytes, 1: bits

################################
# Web
################################

vnstat_web_subdomain: "{{ vnstat_name }}"
vnstat_web_domain: "{{ user.domain }}"
vnstat_web_port: "8685"
vnstat_web_url: "{{ 'https://' + (vnstat_web_subdomain + '.' + vnstat_web_domain
                 if (vnstat_web_subdomain | length > 0)
                 else vnstat_web_domain) }}"

################################
# DNS
################################

vnstat_dns_record: "{{ vnstat_web_subdomain }}"
vnstat_dns_zone: "{{ vnstat_web_domain }}"
vnstat_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

vnstat_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
vnstat_traefik_middleware_default: "{{ traefik_default_middleware }}"
vnstat_traefik_middleware_custom: ""
vnstat_traefik_certresolver: "{{ traefik_default_certresolver }}"
vnstat_traefik_enabled: true
vnstat_traefik_api_enabled: false
vnstat_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
vnstat_docker_container: "{{ vnstat_name }}"

# Image
vnstat_docker_image_pull: true
vnstat_docker_image_tag: "latest"
vnstat_docker_image: "vergoh/vnstat:{{ vnstat_docker_image_tag }}"

# Envs
vnstat_docker_envs_default:
  TZ: "{{ tz }}"
  HTTP_PORT: "8685"
  PAGE_REFRESH: "{{ vnstat_page_refresh }}"
  RATE_UNIT: "{{ vnstat_rate_unit }}"
  RUN_VNSTATD: "0"
vnstat_docker_envs_custom: {}
vnstat_docker_envs: "{{ vnstat_docker_envs_default
                        | combine(vnstat_docker_envs_custom) }}"

# Volumes
vnstat_docker_volumes_default:
  - "vnstat:/var/lib/vnstat:ro"
vnstat_docker_volumes_custom: []
vnstat_docker_volumes: "{{ vnstat_docker_volumes_default
                           + vnstat_docker_volumes_custom }}"

# Hostname
vnstat_docker_hostname: "{{ vnstat_name }}"

# Networks
vnstat_docker_networks_alias: "{{ vnstat_name }}"
vnstat_docker_networks_default: []
vnstat_docker_networks_custom: []
vnstat_docker_networks: "{{ docker_networks_common
                            + vnstat_docker_networks_default
                            + vnstat_docker_networks_custom }}"

# Restart Policy
vnstat_docker_restart_policy: unless-stopped

# State
vnstat_docker_state: started

# Force Kill
vnstat_docker_force_kill: true
