##########################################################################
# Title:         Sandbox: Nextcloud | Default Variables                  #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

nextcloud_name: nextcloud

################################
# Settings
################################

nextcloud_data_directory: "/var/www/html/data"
nextcloud_php_memory_limit: "512M"
nextcloud_php_upload_limit: "512M"

################################
# Paths
################################

nextcloud_role_paths_folder: "{{ nextcloud_name }}"
nextcloud_role_paths_location: "{{ server_appdata_path }}/{{ nextcloud_role_paths_folder }}"
nextcloud_role_paths_folders_list:
  - "{{ nextcloud_role_paths_location }}"

################################
# Web
################################

nextcloud_role_web_subdomain: "{{ nextcloud_name }}"
nextcloud_role_web_domain: "{{ user.domain }}"
nextcloud_role_web_port: "80"
nextcloud_role_web_url: "{{ 'https://' + (nextcloud_role_web_subdomain + '.' + nextcloud_role_web_domain
                    if (nextcloud_role_web_subdomain | length > 0)
                    else nextcloud_role_web_domain) }}"

################################
# DNS
################################

nextcloud_role_dns_record: "{{ nextcloud_role_web_subdomain }}"
nextcloud_role_dns_zone: "{{ nextcloud_role_web_domain }}"
nextcloud_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

nextcloud_role_traefik_sso_middleware: ""
nextcloud_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
nextcloud_role_traefik_middleware_custom: ""
nextcloud_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
nextcloud_role_traefik_enabled: true
nextcloud_role_traefik_api_enabled: false
nextcloud_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
nextcloud_role_docker_container: "{{ nextcloud_name }}"

# Image
nextcloud_role_docker_image_pull: true
nextcloud_role_docker_image_tag: "latest"
nextcloud_role_docker_image: "nextcloud:{{ nextcloud_role_docker_image_tag }}"

# Envs
nextcloud_role_docker_envs_default:
  TZ: "{{ tz }}"
  NEXTCLOUD_ADMIN_USER: "{{ user.name }}"
  NEXTCLOUD_ADMIN_PASSWORD: "{{ user.pass }}"
  NEXTCLOUD_TRUSTED_DOMAINS: "{{ nextcloud_role_web_subdomain + '.' + nextcloud_role_web_domain }}"
  NEXTCLOUD_DATA_DIR: "{{ nextcloud_data_directory }}"
  MYSQL_DATABASE: "nextcloud"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "{{ mariadb_role_docker_env_password }}"
  MYSQL_HOST: "mariadb"
  OVERWRITEHOST: "{{ nextcloud_role_web_subdomain + '.' + nextcloud_role_web_domain }}"
  OVERWRITEPROTOCOL: "https"
  OVERWRITECLIURL: "https://{{ nextcloud_role_web_subdomain + '.' + nextcloud_role_web_domain }}"
  PHP_MEMORY_LIMIT: "{{ nextcloud_php_memory_limit }}"
  PHP_UPLOAD_LIMIT: "{{ nextcloud_php_upload_limit }}"
  TRUSTED_PROXIES: "172.19.0.0/16"
nextcloud_role_docker_envs_custom: {}
nextcloud_role_docker_envs: "{{ nextcloud_role_docker_envs_default
                           | combine(nextcloud_role_docker_envs_custom) }}"

# Volumes
nextcloud_role_docker_volumes_default:
  - "{{ nextcloud_role_paths_location }}:/var/www/html"
nextcloud_role_docker_volumes_custom: []
nextcloud_role_docker_volumes: "{{ nextcloud_role_docker_volumes_default
                              + nextcloud_role_docker_volumes_custom }}"

# Labels
nextcloud_role_docker_labels_default:
  traefik.http.middlewares.nextcloud-caldav.replacepathregex.regex: "^/.well-known/ca(l|rd)dav"
  traefik.http.middlewares.nextcloud-caldav.replacepathregex.replacement: "/remote.php/dav/"
nextcloud_role_docker_labels_custom: {}
nextcloud_role_docker_labels: "{{ nextcloud_role_docker_labels_default
                             | combine(nextcloud_role_docker_labels_custom) }}"

# Hostname
nextcloud_role_docker_hostname: "{{ nextcloud_name }}"

# Networks
nextcloud_role_docker_networks_alias: "{{ nextcloud_name }}"
nextcloud_role_docker_networks_default: []
nextcloud_role_docker_networks_custom: []
nextcloud_role_docker_networks: "{{ docker_networks_common
                               + nextcloud_role_docker_networks_default
                               + nextcloud_role_docker_networks_custom }}"

# Restart Policy
nextcloud_role_docker_restart_policy: unless-stopped

# State
nextcloud_role_docker_state: started

# User
nextcloud_role_docker_user: "{{ uid }}:{{ gid }}"

# Dependencies
nextcloud_depends_on: "mariadb"
nextcloud_depends_on_delay: "0"
nextcloud_depends_on_healthchecks: "false"
