#########################################################################
# Title:            Sandbox: Deluge VPN                                 #
# Author(s):        maximuskowalski, Migz93, salty                      #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Check for required variables
  ansible.builtin.fail:
    msg: "You need to set delugevpn_role_vpn_user and delugevpn_role_vpn_pass when delugevpn_role_vpn_prov is set to pia using the inventory."
  when: (not continuous_integration)
        and ((delugevpn_role_vpn_user | length == 0) or (delugevpn_role_vpn_pass | length == 0))
        and (delugevpn_role_vpn_prov == "pia")

- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('role_var', '_dns_record') }}"
    dns_zone: "{{ lookup('role_var', '_dns_zone') }}"
    dns_proxy: "{{ lookup('role_var', '_dns_proxy') }}"

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
