##########################################################################
# Title:         Sandbox: Wordpress | Default Variables                  #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

wordpress_instances: ["wordpress"]

################################
# Paths
################################

wordpress_role_paths_folder: "{{ wordpress_name }}"
wordpress_role_paths_location: "{{ server_appdata_path }}/{{ wordpress_role_paths_folder }}"
wordpress_role_paths_folders_list:
  - "{{ wordpress_role_paths_location }}"
wordpress_role_paths_recursive: true

################################
# Web
################################

wordpress_role_web_subdomain: "{{ wordpress_name }}"
wordpress_role_web_domain: "{{ user.domain }}"
wordpress_role_web_port: "80"
wordpress_role_web_url: "{{ 'https://' + (lookup('vars', wordpress_name + '_web_subdomain', default=wordpress_role_web_subdomain) + '.' + lookup('vars', wordpress_name + '_web_domain', default=wordpress_role_web_domain)
                         if (lookup('vars', wordpress_name + '_web_subdomain', default=wordpress_role_web_subdomain) | length > 0)
                         else lookup('vars', wordpress_name + '_web_domain', default=wordpress_role_web_domain)) }}"

################################
# DNS
################################

wordpress_role_dns_record: "{{ lookup('vars', wordpress_name + '_web_subdomain', default=wordpress_role_web_subdomain) }}"
wordpress_role_dns_zone: "{{ lookup('vars', wordpress_name + '_web_domain', default=wordpress_role_web_domain) }}"
wordpress_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

wordpress_role_traefik_sso_middleware: ""
wordpress_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
wordpress_role_traefik_middleware_custom: ""
wordpress_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
wordpress_role_traefik_enabled: true
wordpress_role_traefik_api_enabled: false
wordpress_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
wordpress_role_docker_container: "{{ wordpress_name }}"

# Image
wordpress_role_docker_image_pull: true
wordpress_role_docker_image_repo: "wordpress"
wordpress_role_docker_image_tag: "latest"
wordpress_role_docker_image: "{{ lookup('vars', wordpress_name + '_docker_image_repo', default=wordpress_role_docker_image_repo)
                                 + ':' + lookup('vars', wordpress_name + '_docker_image_tag', default=wordpress_role_docker_image_tag) }}"

# Envs
wordpress_role_docker_envs_default:
  TZ: "{{ tz }}"
  WORDPRESS_DB_HOST: "mariadb:3306"
  WORDPRESS_DB_USER: "root"
  WORDPRESS_DB_PASSWORD: "password321"
  WORDPRESS_DB_NAME: "{{ wordpress_name }}"
wordpress_role_docker_envs_custom: {}
wordpress_role_docker_envs: "{{ lookup('vars', wordpress_name + '_docker_envs_default', default=wordpress_role_docker_envs_default)
                                | combine(lookup('vars', wordpress_name + '_docker_envs_custom', default=wordpress_role_docker_envs_custom)) }}"

# Volumes
wordpress_role_docker_volumes_default:
  - "{{ wordpress_role_paths_location }}:/var/www/html"
wordpress_role_docker_volumes_custom: []
wordpress_role_docker_volumes: "{{ lookup('vars', wordpress_name + '_docker_volumes_default', default=wordpress_role_docker_volumes_default)
                                   + lookup('vars', wordpress_name + '_docker_volumes_custom', default=wordpress_role_docker_volumes_custom) }}"

# Hostname
wordpress_role_docker_hostname: "{{ wordpress_name }}"

# Networks
wordpress_role_docker_networks_alias: "{{ wordpress_name }}"
wordpress_role_docker_networks_default: []
wordpress_role_docker_networks_custom: []
wordpress_role_docker_networks: "{{ docker_networks_common
                                    + lookup('vars', wordpress_name + '_docker_networks_default', default=wordpress_role_docker_networks_default)
                                    + lookup('vars', wordpress_name + '_docker_networks_custom', default=wordpress_role_docker_networks_custom) }}"

# Restart Policy
wordpress_role_docker_restart_policy: unless-stopped

# State
wordpress_role_docker_state: started

# User
wordpress_role_docker_user: "{{ uid }}:{{ gid }}"

# Dependencies
wordpress_role_depends_on: "mariadb"
wordpress_role_depends_on_delay: "0"
wordpress_role_depends_on_healthchecks: "false"
