##########################################################################
# Title:         Sandbox: PGAdmin | Default Variables                    #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

pgadmin_name: pgadmin

################################
# Web
################################

pgadmin_web_subdomain: "{{ pgadmin_name }}"
pgadmin_web_domain: "{{ user.domain }}"
pgadmin_web_port: "80"
pgadmin_web_url: "{{ 'https://' + (pgadmin_web_subdomain + '.' + pgadmin_web_domain
                  if (pgadmin_web_subdomain | length > 0)
                  else pgadmin_web_domain) }}"

################################
# DNS
################################

pgadmin_dns_record: "{{ pgadmin_web_subdomain }}"
pgadmin_dns_zone: "{{ pgadmin_web_domain }}"
pgadmin_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

pgadmin_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
pgadmin_traefik_middleware_default: "{{ traefik_default_middleware }}"
pgadmin_traefik_middleware_custom: ""
pgadmin_traefik_certresolver: "{{ traefik_default_certresolver }}"
pgadmin_traefik_enabled: true
pgadmin_traefik_api_enabled: false
pgadmin_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
pgadmin_docker_container: "{{ pgadmin_name }}"

# Image
pgadmin_docker_image_pull: true
pgadmin_docker_image_tag: "latest"
pgadmin_docker_image: "dpage/pgadmin4:{{ pgadmin_docker_image_tag }}"

# Envs
pgadmin_docker_envs_default:
  PGADMIN_DEFAULT_EMAIL: "{{ user.email }}"
  PGADMIN_DEFAULT_PASSWORD: "{{ user.pass }}"
pgadmin_docker_envs_custom: {}
pgadmin_docker_envs: "{{ pgadmin_docker_envs_default
                         | combine(pgadmin_docker_envs_custom) }}"

# Volumes
pgadmin_docker_volumes_default:
  - "pgadmin:/var/lib/pgadmin"
pgadmin_docker_volumes_custom: []
pgadmin_docker_volumes: "{{ pgadmin_docker_volumes_default
                            + pgadmin_docker_volumes_custom }}"

# Hostname
pgadmin_docker_hostname: "{{ pgadmin_name }}"

# Networks
pgadmin_docker_networks_alias: "{{ pgadmin_name }}"
pgadmin_docker_networks_default: []
pgadmin_docker_networks_custom: []
pgadmin_docker_networks: "{{ docker_networks_common
                             + pgadmin_docker_networks_default
                             + pgadmin_docker_networks_custom }}"

# Restart Policy
pgadmin_docker_restart_policy: unless-stopped

# State
pgadmin_docker_state: started
