#########################################################################
# Title:            Sandbox: Duplicati                                  #
# Author(s):        Derek Z, JigSawFr                                   #
# URL:              https://github.com/saltyorg/Sandbox                 #
# URL:              https://github.com/linuxserver/docker-duplicati     #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

duplicati_name: duplicati

################################
# Paths
################################

duplicati_role_paths_folder: "{{ duplicati_name }}"
duplicati_role_paths_location: "{{ server_appdata_path }}/{{ duplicati_role_paths_folder }}"
duplicati_role_paths_folders_list:
  - "{{ duplicati_role_paths_location }}"

################################
# Web
################################

duplicati_role_web_subdomain: "{{ duplicati_name }}"
duplicati_role_web_domain: "{{ user.domain }}"
duplicati_role_web_port: "8200"
duplicati_role_web_url: "{{ 'https://' + (duplicati_role_web_subdomain + '.' + duplicati_role_web_domain
                    if (duplicati_role_web_subdomain | length > 0)
                    else duplicati_role_web_domain) }}"

################################
# DNS
################################

duplicati_role_dns_record: "{{ duplicati_role_web_subdomain }}"
duplicati_role_dns_zone: "{{ duplicati_role_web_domain }}"
duplicati_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

duplicati_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
duplicati_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
duplicati_role_traefik_middleware_custom: ""
duplicati_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
duplicati_role_traefik_enabled: true
duplicati_role_traefik_api_enabled: true
duplicati_role_traefik_api_endpoint: "PathPrefix(`/api`)"

################################
# Docker
################################

# Container
duplicati_role_docker_container: "{{ duplicati_name }}"

# Image
duplicati_role_docker_image_pull: true
duplicati_role_docker_image_tag: "latest"
duplicati_role_docker_image: "linuxserver/duplicati:{{ duplicati_role_docker_image_tag }}"

# Envs
duplicati_role_docker_envs_default:
  TZ: "{{ tz }}"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
duplicati_role_docker_envs_custom: {}
duplicati_role_docker_envs: "{{ duplicati_role_docker_envs_default
                           | combine(duplicati_role_docker_envs_custom) }}"

# Volumes
duplicati_role_docker_volumes_default:
  - "{{ duplicati_role_paths_location }}:/config"
  - "/opt:/saltbox/opt"
  - "/srv/git/saltbox:/saltbox/saltbox"
duplicati_role_docker_volumes_custom: []
duplicati_role_docker_volumes: "{{ duplicati_role_docker_volumes_default
                              + duplicati_role_docker_volumes_custom }}"

# Hostname
duplicati_role_docker_hostname: "{{ duplicati_name }}"

# Networks
duplicati_role_docker_networks_alias: "{{ duplicati_name }}"
duplicati_role_docker_networks_default: []
duplicati_role_docker_networks_custom: []
duplicati_role_docker_networks: "{{ docker_networks_common
                               + duplicati_role_docker_networks_default
                               + duplicati_role_docker_networks_custom }}"

# Restart Policy
duplicati_role_docker_restart_policy: unless-stopped

# State
duplicati_role_docker_state: started
