#########################################################################
# Title:            Sandbox: Transmission                               #
# Author(s):        salty                                               #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

transmission_instances: ["transmission"]

################################
# Paths
################################

transmission_paths_folder: "{{ transmission_name }}"
transmission_paths_location: "{{ server_appdata_path }}/{{ transmission_paths_folder }}"
transmission_paths_downloads_location: "{{ downloads_torrents_path }}/{{ transmission_paths_folder }}"
transmission_paths_folders_list:
  - "{{ transmission_paths_location }}"
  - "{{ transmission_paths_downloads_location }}"
  - "{{ transmission_paths_downloads_location }}/completed"
  - "{{ transmission_paths_downloads_location }}/incoming"
  - "{{ transmission_paths_downloads_location }}/watched"
  - "{{ transmission_paths_downloads_location }}/torrents"
transmission_paths_setttings_location: "{{ transmission_paths_location }}/settings.json"

################################
# Web
################################

transmission_web_subdomain: "{{ transmission_name }}"
transmission_web_domain: "{{ user.domain }}"
transmission_web_port: "9091"
transmission_web_url: "{{ 'https://' + (lookup('vars', transmission_name + '_web_subdomain', default=transmission_web_subdomain) + '.' + lookup('vars', transmission_name + '_web_domain', default=transmission_web_domain)
                       if (lookup('vars', transmission_name + '_web_subdomain', default=transmission_web_subdomain) | length > 0)
                       else lookup('vars', transmission_name + '_web_domain', default=transmission_web_domain)) }}"

################################
# DNS
################################

transmission_dns_record: "{{ lookup('vars', transmission_name + '_web_subdomain', default=transmission_web_subdomain) }}"
transmission_dns_zone: "{{ lookup('vars', transmission_name + '_web_domain', default=transmission_web_domain) }}"
transmission_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

transmission_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
transmission_traefik_middleware_default: "{{ traefik_default_middleware }}"
transmission_traefik_middleware_custom: ""
transmission_traefik_certresolver: "{{ traefik_default_certresolver }}"
transmission_traefik_enabled: true
transmission_traefik_api_enabled: true
transmission_traefik_api_endpoint: "PathPrefix(`/rpc`)"

################################
# Docker
################################

# Container
transmission_docker_container: "{{ transmission_name }}"

# Image
transmission_docker_image_pull: true
transmission_docker_image_repo: "lscr.io/linuxserver/transmission"
transmission_docker_image_tag: "latest"
transmission_docker_image: "{{ lookup('vars', transmission_name + '_docker_image_repo', default=transmission_docker_image_repo)
                               + ':' + lookup('vars', transmission_name + '_docker_image_tag', default=transmission_docker_image_tag) }}"

# Ports
# - Internal and External ports need to match for the next set of ports
# - Lookup available ports and set docker ports accordingly
transmission_docker_ports_51413: "{{ port_lookup_51413.meta.port
                                  if (port_lookup_51413.meta.port is defined) and (port_lookup_51413.meta.port | trim | length > 0)
                                  else '51413' }}"
transmission_docker_ports_defaults:
  - "{{ transmission_docker_ports_51413 }}:{{ transmission_docker_ports_51413 }}"
  - "{{ transmission_docker_ports_51413 }}:{{ transmission_docker_ports_51413 }}/udp"
transmission_docker_ports_custom: []
transmission_docker_ports: "{{ lookup('vars', transmission_name + '_docker_ports_defaults', default=transmission_docker_ports_defaults)
                               + lookup('vars', transmission_name + '_docker_ports_custom', default=transmission_docker_ports_custom) }}"

# Envs
transmission_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  UMASK: "002"
  USER: "{{ user.name }}"
  PASS: "{{ user.pass }}"
transmission_docker_envs_custom: {}
transmission_docker_envs: "{{ lookup('vars', transmission_name + '_docker_envs_default', default=transmission_docker_envs_default)
                              | combine(lookup('vars', transmission_name + '_docker_envs_custom', default=transmission_docker_envs_custom)) }}"

# Volumes
transmission_docker_volumes_default:
  - "{{ transmission_paths_location }}:/config"
  - "{{ server_appdata_path }}/scripts:/scripts"
  - "{{ transmission_paths_downloads_location }}/watched:/watch"
transmission_docker_volumes_custom: []
transmission_docker_volumes: "{{ lookup('vars', transmission_name + '_docker_volumes_default', default=transmission_docker_volumes_default)
                                 + lookup('vars', transmission_name + '_docker_volumes_custom', default=transmission_docker_volumes_custom) }}"

# Hostname
transmission_docker_hostname: "{{ transmission_name }}"

# Networks
transmission_docker_networks_alias: "{{ transmission_name }}"
transmission_docker_networks_default: []
transmission_docker_networks_custom: []
transmission_docker_networks: "{{ docker_networks_common
                                  + lookup('vars', transmission_name + '_docker_networks_default', default=transmission_docker_networks_default)
                                  + lookup('vars', transmission_name + '_docker_networks_custom', default=transmission_docker_networks_custom) }}"

# Restart Policy
transmission_docker_restart_policy: unless-stopped

# Stop Timeout
transmission_docker_stop_timeout: 900

# State
transmission_docker_state: started
