#########################################################################
# Title:            Sandbox: Sshwifty                                   #
# Author(s):        astromd, kowalski                                   #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

sshwifty_name: sshwifty

################################
# Paths
################################

sshwifty_role_paths_folder: "{{ sshwifty_name }}"
sshwifty_role_paths_location: "{{ server_appdata_path }}/{{ sshwifty_role_paths_folder }}"
sshwifty_role_paths_folders_list:
  - "{{ sshwifty_role_paths_location }}"
  - "{{ sshwifty_role_paths_location }}/config"
sshwifty_role_paths_config_location: "{{ sshwifty_role_paths_location }}/config/sshwifty.conf.json"

################################
# Web
################################

sshwifty_role_web_subdomain: "{{ sshwifty_name }}"
sshwifty_role_web_domain: "{{ user.domain }}"
sshwifty_role_web_port: "8182"
sshwifty_role_web_url: "{{ 'https://' + (sshwifty_role_web_subdomain + '.' + sshwifty_role_web_domain
                        if (sshwifty_role_web_subdomain | length > 0)
                        else sshwifty_role_web_domain) }}"

################################
# DNS
################################

sshwifty_role_dns_record: "{{ sshwifty_role_web_subdomain }}"
sshwifty_role_dns_zone: "{{ sshwifty_role_web_domain }}"
sshwifty_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

sshwifty_role_traefik_sso_middleware: ""
sshwifty_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
sshwifty_role_traefik_middleware_custom: ""
sshwifty_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
sshwifty_role_traefik_enabled: true
sshwifty_role_traefik_api_enabled: false
sshwifty_role_traefik_api_endpoint: ""
sshwifty_role_traefik_error_pages_enabled: false

################################
# Docker
################################

# Container
sshwifty_role_docker_container: "{{ sshwifty_name }}"

# Image
sshwifty_role_docker_image_pull: true
sshwifty_role_docker_image_tag: "latest"
sshwifty_role_docker_image: "niruix/sshwifty:{{ sshwifty_role_docker_image_tag }}"

# Envs
sshwifty_role_docker_envs_default:
  SSHWIFTY_CONFIG: "/config/sshwifty.conf.json"
sshwifty_role_docker_envs_custom: {}
sshwifty_role_docker_envs: "{{ sshwifty_role_docker_envs_default
                               | combine(sshwifty_role_docker_envs_custom) }}"

# Volumes
sshwifty_role_docker_volumes_default:
  - "{{ sshwifty_role_paths_location }}/config:/config"
sshwifty_role_docker_volumes_custom: []
sshwifty_role_docker_volumes: "{{ sshwifty_role_docker_volumes_default
                                  + sshwifty_role_docker_volumes_custom }}"

# Hostname
sshwifty_role_docker_hostname: "{{ sshwifty_name }}"

# Networks
sshwifty_role_docker_networks_alias: "{{ sshwifty_name }}"
sshwifty_role_docker_networks_default: []
sshwifty_role_docker_networks_custom: []
sshwifty_role_docker_networks: "{{ docker_networks_common
                                   + sshwifty_role_docker_networks_default
                                   + sshwifty_role_docker_networks_custom }}"

# Restart Policy
sshwifty_role_docker_restart_policy: unless-stopped

# State
sshwifty_role_docker_state: started

# User
sshwifty_role_docker_user: "{{ uid }}:{{ gid }}"
