##########################################################################
# Title:            Sandbox: Lunasea | Default Variables                 #
# Author(s):        JigSawFr                                             #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

lunasea_name: lunasea

################################
# Paths
################################

lunasea_role_paths_folder: "{{ lunasea_name }}"
lunasea_role_paths_location: {}
lunasea_role_paths_folders_list: []
################################
# Web
################################

lunasea_role_web_subdomain: "{{ lunasea_name }}"
lunasea_role_web_domain: "{{ user.domain }}"
lunasea_role_web_port: "80"
lunasea_role_web_url: "{{ 'https://' + (lunasea_role_web_subdomain + '.' + lunasea_role_web_domain
                  if (lunasea_role_web_subdomain | length > 0)
                  else lunasea_role_web_domain) }}"

################################
# DNS
################################

lunasea_role_dns_record: "{{ lunasea_role_web_subdomain }}"
lunasea_role_dns_zone: "{{ lunasea_role_web_domain }}"
lunasea_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

lunasea_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
lunasea_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
lunasea_role_traefik_middleware_custom: ""
lunasea_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
lunasea_role_traefik_enabled: true
lunasea_role_traefik_api_enabled: false
lunasea_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
lunasea_role_docker_container: "{{ lunasea_name }}"

# Image
lunasea_role_docker_image_pull: true
lunasea_role_docker_image_tag: "stable"
lunasea_role_docker_image: "ghcr.io/jagandeepbrar/lunasea:{{ lunasea_role_docker_image_tag }}"

# Envs
lunasea_role_docker_envs_default:
  TZ: "{{ tz }}"
lunasea_role_docker_envs_custom: {}
lunasea_role_docker_envs: "{{ lunasea_role_docker_envs_default
                         | combine(lunasea_role_docker_envs_custom) }}"

# Hostname
lunasea_role_docker_hostname: "{{ lunasea_name }}"

# Networks
lunasea_role_docker_networks_alias: "{{ lunasea_name }}"
lunasea_role_docker_networks_default: []
lunasea_role_docker_networks_custom: []
lunasea_role_docker_networks: "{{ docker_networks_common
                             + lunasea_role_docker_networks_default
                             + lunasea_role_docker_networks_custom }}"

# Restart Policy
lunasea_role_docker_restart_policy: unless-stopped

# State
lunasea_role_docker_state: started
