##########################################################################
# Title:         Sandbox: xTeve | Default Variables                      #
# Author(s):     Satz, Migz, salty                                       #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

xteve_name: xteve

################################
# Paths
################################

xteve_role_paths_folder: "{{ xteve_name }}"
xteve_role_paths_location: "{{ server_appdata_path }}/{{ xteve_role_paths_folder }}"
xteve_role_paths_folders_list:
  - "{{ xteve_role_paths_location }}"

################################
# Web
################################

xteve_role_web_subdomain: "{{ xteve_name }}"
xteve_role_web_domain: "{{ user.domain }}"
xteve_role_web_port: "34400"
xteve_role_web_url: "{{ 'https://' + (xteve_role_web_subdomain + '.' + xteve_role_web_domain
                     if (xteve_role_web_subdomain | length > 0)
                     else xteve_role_web_domain) }}"

################################
# DNS
################################

xteve_role_dns_record: "{{ xteve_role_web_subdomain }}"
xteve_role_dns_zone: "{{ xteve_role_web_domain }}"
xteve_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

xteve_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
xteve_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
xteve_role_traefik_middleware_custom: ""
xteve_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
xteve_role_traefik_enabled: true
xteve_role_traefik_api_enabled: true
xteve_role_traefik_api_endpoint: "PathPrefix(`/data_images`) || PathPrefix(`/api`)"

################################
# Docker
################################

# Container
xteve_role_docker_container: "{{ xteve_name }}"

# Image
xteve_role_docker_image_pull: true
xteve_role_docker_image_tag: "latest"
xteve_role_docker_image: "dnsforge/xteve:{{ xteve_role_docker_image_tag }}"

# Envs
xteve_role_docker_envs_default:
  TZ: "{{ tz }}"
  XTEVE_BRANCH: "beta"
  XTEVE_UID: "{{ uid }}"
  XTEVE_GID: "{{ gid }}"
  XTEVE_API: "1"
xteve_role_docker_envs_custom: {}
xteve_role_docker_envs: "{{ xteve_role_docker_envs_default
                            | combine(xteve_role_docker_envs_custom) }}"

# Volumes
xteve_role_docker_volumes_default:
  - "{{ xteve_role_paths_location }}/app/config:/home/xteve/conf:rw"
  - "{{ xteve_role_paths_location }}/app/tmp:/tmp/xteve:rw"
  - "{{ xteve_role_paths_location }}/app/guide2go:/home/xteve/guide2go/conf:rw"
xteve_role_docker_volumes_custom: []
xteve_role_docker_volumes: "{{ xteve_role_docker_volumes_default
                               + xteve_role_docker_volumes_custom }}"

# Hostname
xteve_role_docker_hostname: "{{ xteve_name }}"

# Networks
xteve_role_docker_networks_alias: "{{ xteve_name }}"
xteve_role_docker_networks_default: []
xteve_role_docker_networks_custom: []
xteve_role_docker_networks: "{{ docker_networks_common
                                + xteve_role_docker_networks_default
                                + xteve_role_docker_networks_custom }}"

# Restart Policy
xteve_role_docker_restart_policy: unless-stopped

# State
xteve_role_docker_state: started
