##########################################################################
# Title:            Sandbox: n8n-io | Default Variables                  #
# Author(s):        JigSawFr                                             #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

n8n_name: n8n

################################
# Settings
################################

n8n_postgres_name: "{{ n8n_name }}-postgres"
n8n_postgres_docker_env_db: "{{ n8n_name }}"
n8n_postgres_docker_image_tag: "14-alpine"
n8n_postgres_docker_image_repo: "postgres"
n8n_postgres_paths_folder: "{{ n8n_name }}"
n8n_postgres_paths_location: "{{ server_appdata_path }}/{{ postgres_paths_folder }}/postgres"

################################
# Paths
################################

n8n_paths_folder: "{{ n8n_name }}"
n8n_paths_location: "{{ server_appdata_path }}/{{ n8n_paths_folder }}/app"
n8n_paths_folders_list:
  - "{{ n8n_paths_location }}"

################################
# Web
################################

n8n_web_subdomain: "{{ n8n_name }}"
n8n_web_domain: "{{ user.domain }}"
n8n_web_port: "5678"
n8n_web_url: "{{ 'https://' + (n8n_web_subdomain + '.' + n8n_web_domain
              if (n8n_web_subdomain | length > 0)
              else n8n_web_domain) }}"

################################
# DNS
################################

n8n_dns_record: "{{ n8n_web_subdomain }}"
n8n_dns_zone: "{{ n8n_web_domain }}"
n8n_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

n8n_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
n8n_traefik_middleware_default: "{{ traefik_default_middleware }}"
n8n_traefik_middleware_custom: ""
n8n_traefik_certresolver: "{{ traefik_default_certresolver }}"
n8n_traefik_enabled: true
n8n_traefik_api_enabled: true
n8n_traefik_api_endpoint: "PathPrefix(`/api`)"

################################
# Docker
################################

# Container
n8n_docker_container: "{{ n8n_name }}"

# Image
n8n_docker_image_pull: true
n8n_docker_image_tag: "latest"
n8n_docker_image: "n8nio/n8n:{{ n8n_docker_image_tag }}"

# Envs
n8n_docker_envs_default:
  GENERIC_TIMEZONE: "{{ tz }}"
  TZ: "{{ tz }}"
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_DATABASE: "{{ n8n_postgres_docker_env_db }}"
  DB_POSTGRESDB_HOST: "{{ n8n_postgres_name }}"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_USER: "{{ postgres_docker_env_user }}"
  DB_POSTGRESDB_PASSWORD: "{{ postgres_docker_env_password }}"
  N8N_EDITOR_BASE_URL: "{{ n8n_web_url }}"
  N8N_DIAGNOSTICS_ENABLED: "false"
  N8N_HIRING_BANNER_ENABLED: "false"
  N8N_USER_MANAGEMENT_DISABLED: "true"
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
n8n_docker_envs_custom: {}
n8n_docker_envs: "{{ n8n_docker_envs_default
                     | combine(n8n_docker_envs_custom) }}"

# Volumes
n8n_docker_volumes_default:
  - "{{ n8n_paths_location }}:/home/node/.n8n"
n8n_docker_volumes_custom: []
n8n_docker_volumes: "{{ n8n_docker_volumes_default
                        + n8n_docker_volumes_custom }}"

# Hostname
n8n_docker_hostname: "{{ n8n_name }}"

# Networks
n8n_docker_networks_alias: "{{ n8n_name }}"
n8n_docker_networks_default: []
n8n_docker_networks_custom: []
n8n_docker_networks: "{{ docker_networks_common
                         + n8n_docker_networks_default
                         + n8n_docker_networks_custom }}"

# Restart Policy
n8n_docker_restart_policy: unless-stopped

# State
n8n_docker_state: started

# Dependencies
n8n_depends_on: "{{ n8n_postgres_name }}"
n8n_depends_on_delay: "0"
n8n_depends_on_healthchecks: "false"

# User
n8n_docker_user: "{{ uid }}:{{ gid }}"
