##########################################################################
# Title:         Sandbox: A-train | Default Variables                    #
# Author(s):     hackmonker                                              #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

a_train_name: a-train

################################
# Paths
################################

a_train_paths_folder: "{{ a_train_name }}"
a_train_paths_location: "{{ server_appdata_path }}/{{ a_train_paths_folder }}"
a_train_paths_config_location: "{{ a_train_paths_location }}/a-train.toml"
a_train_paths_sa_location: "{{ a_train_paths_location }}/account.json"
a_train_paths_rclone_config_location: "/home/{{ user.name }}/.config/rclone/rclone.conf"
a_train_paths_folders_list:
  - "{{ a_train_paths_location }}"

################################
# Docker
################################

# Container
a_train_docker_container: "{{ a_train_name }}"

# Image
a_train_docker_image_pull: true
a_train_docker_image_tag: "latest"
a_train_docker_image: "ghcr.io/m-rots/a-train:{{ a_train_docker_image_tag }}"

# Envs
a_train_docker_envs_default:
  TZ: "{{ tz }}"
a_train_docker_envs_custom: {}
a_train_docker_envs: "{{ a_train_docker_envs_default
                         | combine(a_train_docker_envs_custom) }}"

# Volumes
a_train_docker_volumes_default:
  - "{{ a_train_paths_location }}:/data"
a_train_docker_volumes_custom: []
a_train_docker_volumes: "{{ a_train_docker_volumes_default
                            + a_train_docker_volumes_custom }}"

# Hostname
a_train_docker_hostname: "{{ a_train_name }}"

# Networks
a_train_docker_networks_alias: "{{ a_train_name }}"
a_train_docker_networks_default: []
a_train_docker_networks_custom: []
a_train_docker_networks: "{{ docker_networks_common
                             + a_train_docker_networks_default
                             + a_train_docker_networks_custom }}"

# Restart Policy
a_train_docker_restart_policy: unless-stopped

# State
a_train_docker_state: started

# User
a_train_docker_user: "{{ uid }}:{{ gid }}"
