#########################################################################
# Title:            Sandbox: mqtt                                       #
# Author(s):        CHAIR/Raneydazed                                    #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Check if `{{ lookup('role_var', '_paths_config_location', role='mqtt') | basename }}` exists
  ansible.builtin.stat:
    path: "{{ lookup('role_var', '_paths_config_location', role='mqtt') }}"
  register: mqtt_config

- name: Import default config
  ansible.builtin.template:
    src: mosquitto.conf.j2
    dest: "{{ lookup('role_var', '_paths_config_location', role='mqtt') }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0664"

  when: (not mqtt_config.stat.exists) and (not continuous_integration)

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
