##########################################################################
# Title:            Sandbox: tvheadend | Default Variables               #
# Author(s):        JigSawFr                                             #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

tvheadend_name: tvheadend

################################
# Paths
################################

tvheadend_role_paths_folder: "{{ tvheadend_name }}"
tvheadend_role_paths_location: "{{ server_appdata_path }}/{{ tvheadend_role_paths_folder }}"
tvheadend_role_paths_downloads_location: "{{ downloads_root_path }}/{{ tvheadend_role_paths_folder }}"
tvheadend_role_paths_folders_list:
  - "{{ tvheadend_role_paths_location }}"
  - "{{ tvheadend_role_paths_downloads_location }}"


################################
# Web
################################

tvheadend_role_web_subdomain: "{{ tvheadend_name }}"
tvheadend_role_web_domain: "{{ user.domain }}"
tvheadend_role_web_port: "9981"
tvheadend_role_web_url: "{{ 'https://' + (tvheadend_role_web_subdomain + '.' + tvheadend_role_web_domain
                    if (tvheadend_role_web_subdomain | length > 0)
                    else tvheadend_role_web_domain) }}"

################################
# DNS
################################

tvheadend_role_dns_record: "{{ tvheadend_role_web_subdomain }}"
tvheadend_role_dns_zone: "{{ tvheadend_role_web_domain }}"
tvheadend_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

tvheadend_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
tvheadend_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
tvheadend_role_traefik_middleware_custom: ""
tvheadend_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
tvheadend_role_traefik_enabled: true
tvheadend_role_traefik_api_enabled: false
tvheadend_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
tvheadend_role_docker_container: "{{ tvheadend_name }}"

# Image
tvheadend_role_docker_image_pull: true
tvheadend_role_docker_image_tag: "latest"
tvheadend_role_docker_image: "lscr.io/linuxserver/tvheadend:{{ tvheadend_role_docker_image_tag }}"

# Envs
tvheadend_role_docker_envs_default:
  TZ: "{{ tz }}"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
tvheadend_role_docker_envs_custom: {}
tvheadend_role_docker_envs: "{{ tvheadend_role_docker_envs_default
                           | combine(tvheadend_role_docker_envs_custom) }}"

# Volumes
tvheadend_role_docker_volumes_default:
  - "{{ tvheadend_role_paths_location }}:/config"
  - "{{ tvheadend_role_paths_downloads_location }}:/recordings"
tvheadend_role_docker_volumes_custom: []
tvheadend_role_docker_volumes: "{{ tvheadend_role_docker_volumes_default
                              + tvheadend_role_docker_volumes_custom }}"

# Hostname
tvheadend_role_docker_hostname: "{{ tvheadend_name }}"

# Networks
tvheadend_role_docker_networks_alias: "{{ tvheadend_name }}"
tvheadend_role_docker_networks_default: []
tvheadend_role_docker_networks_custom: []
tvheadend_role_docker_networks: "{{ docker_networks_common
                               + tvheadend_role_docker_networks_default
                               + tvheadend_role_docker_networks_custom }}"

# Restart Policy
tvheadend_role_docker_restart_policy: unless-stopped

# State
tvheadend_role_docker_state: started
