########################################################################
# Title:         Sandbox: WatchState | Default Variables               #
# Author(s):     keldian                                               #
# URL:           https://github.com/saltyorg/Sandbox                   #
# --                                                                   #
########################################################################
#                   GNU General Public License v3.0                    #
########################################################################
---
################################
# Basics
################################

watchstate_instances: ["watchstate"]

################################
# Settings
################################

watchstate_api_auto: true
watchstate_trust_proxy: true
watchstate_secure_api_endpoints: true

################################
# Paths
################################

watchstate_role_paths_folder: "{{ watchstate_name }}"
watchstate_role_paths_location: "{{ server_appdata_path }}/{{ watchstate_role_paths_folder }}"
watchstate_role_paths_folders_list:
  - "{{ watchstate_role_paths_location }}"

################################
# Web
################################

watchstate_role_web_subdomain: "{{ watchstate_name }}"
watchstate_role_web_domain: "{{ user.domain }}"
watchstate_role_web_port: "8080"
watchstate_role_web_url: "{{ 'https://' + (lookup('vars', watchstate_name + '_web_subdomain', default=watchstate_role_web_subdomain)
                             + '.' + lookup('vars', watchstate_name + '_web_domain', default=watchstate_role_web_domain)
                          if (lookup('vars', watchstate_name + '_web_subdomain', default=watchstate_role_web_subdomain) | length > 0)
                          else lookup('vars', watchstate_name + '_web_domain', default=watchstate_role_web_domain)) }}"

################################
# DNS
################################

watchstate_role_dns_record: "{{ lookup('vars', watchstate_name + '_web_subdomain', default=watchstate_role_web_subdomain) }}"
watchstate_role_dns_zone: "{{ lookup('vars', watchstate_name + '_web_domain', default=watchstate_role_web_domain) }}"
watchstate_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

watchstate_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
watchstate_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
watchstate_role_traefik_middleware_custom: ""
watchstate_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
watchstate_role_traefik_enabled: true
watchstate_role_traefik_api_enabled: true
watchstate_role_traefik_api_endpoint: "PathRegexp(`backend/[^/]+/webhook`)"

################################
# Docker
################################

# Container
watchstate_role_docker_container: "{{ watchstate_name }}"

# Image
watchstate_role_docker_image_pull: true
watchstate_role_docker_image_repo: "ghcr.io/arabcoders/watchstate"
watchstate_role_docker_image_tag: "latest"
watchstate_role_docker_image: "{{ lookup('vars', watchstate_name + '_docker_image_repo', default=watchstate_role_docker_image_repo)
                                  + ':' + lookup('vars', watchstate_name + '_docker_image_tag', default=watchstate_role_docker_image_tag) }}"

# Envs
watchstate_role_docker_envs_default:
  WS_TZ: "{{ tz }}"
  WS_API_AUTO: "{{ 'true' if watchstate_api_auto else omit }}"
  WS_TRUST_PROXY: "{{ 'true' if watchstate_trust_proxy else omit }}"
  WS_SECURE_API_ENDPOINTS: "{{ 'true' if watchstate_secure_api_endpoints else omit }}"
watchstate_role_docker_envs_custom: {}
watchstate_role_docker_envs: "{{ lookup('vars', watchstate_name + '_docker_envs_default', default=watchstate_role_docker_envs_default)
                                 | combine(lookup('vars', watchstate_name + '_docker_envs_custom', default=watchstate_role_docker_envs_custom)) }}"

# Volumes
watchstate_role_docker_volumes_default:
  - "{{ watchstate_role_paths_location }}:/config"
watchstate_role_docker_volumes_custom: []
watchstate_role_docker_volumes: "{{ lookup('vars', watchstate_name + '_docker_volumes_default', default=watchstate_role_docker_volumes_default)
                                    + lookup('vars', watchstate_name + '_docker_volumes_custom', default=watchstate_role_docker_volumes_custom) }}"

# Hostname
watchstate_role_docker_hostname: "{{ watchstate_name }}"

# Networks
watchstate_role_docker_networks_alias: "{{ watchstate_name }}"
watchstate_role_docker_networks_default: []
watchstate_role_docker_networks_custom: []
watchstate_role_docker_networks: "{{ docker_networks_common
                                     + lookup('vars', watchstate_name + '_docker_networks_default', default=watchstate_role_docker_networks_default)
                                     + lookup('vars', watchstate_name + '_docker_networks_custom', default=watchstate_role_docker_networks_custom) }}"

# Restart Policy
watchstate_role_docker_restart_policy: unless-stopped

# State
watchstate_role_docker_state: started

# User
watchstate_role_docker_user: "{{ uid }}:{{ gid }}"
