#########################################################################
# Title:            Saltbox: minecraft                                  #
# Author(s):        jolbol1                                             #
# URL:              https://github.com/saltyorg/Saltbox                 #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('role_var', '_dns_record') }}"
    dns_zone: "{{ lookup('role_var', '_dns_zone') }}"
    dns_proxy: "{{ lookup('role_var', '_dns_proxy') }}"

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Get next available port within the range of '25565-25665' # noqa fqcn[action]
  find_open_port:
    low_bound: 25565
    high_bound: 25665
    protocol: tcp
  register: port_lookup_minecraft_tcp

- name: Add SRV record
  community.general.cloudflare_dns:
    account_api_key: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    port: "{{ lookup('role_var', '_docker_ports_25565', role='minecraft') }}"
    priority: 1
    proto: tcp
    proxied: false
    record: "{{ _dns_tasker_record }}"
    service: "minecraft"
    solo: true
    state: present
    type: SRV
    value: "{{ _dns_tasker_record }}.{{ _dns_tasker_zone }}"
    weight: 1
    zone: "{{ _dns_tasker_zone }}"
  when: cloudflare_is_enabled

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
