##########################################################################
# Title:            Sandbox: template role                               #
# Author(s):        Raneydazed                                           #
# URL:              https://github.com/saltyorg/Saltbox_mod              #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

photoprism_name: photoprism

################################
# Paths
################################

photoprism_role_paths_folder: "{{ photoprism_name }}"
photoprism_role_paths_location: "{{ server_appdata_path }}/{{ photoprism_role_paths_folder }}"
photoprism_role_paths_folders_list:
  - "{{ photoprism_role_paths_location }}"
  - "{{ photoprism_role_paths_location }}/originals"
  - "{{ photoprism_role_paths_location }}/storage"
  - "{{ photoprism_role_paths_location }}/import"

################################
# Web
################################

photoprism_role_web_subdomain: "{{ photoprism_name }}"
photoprism_role_web_domain: "{{ user.domain }}"
photoprism_role_web_port: "2342"
photoprism_role_web_url: "{{ 'https://' + (photoprism_role_web_subdomain + '.' + photoprism_role_web_domain
                     if (photoprism_role_web_subdomain | length > 0)
                     else photoprism_role_web_domain) }}"

################################
# DNS
################################

photoprism_role_dns_record: "{{ photoprism_role_web_subdomain }}"
photoprism_role_dns_zone: "{{ photoprism_role_web_domain }}"
photoprism_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

photoprism_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
photoprism_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
photoprism_role_traefik_middleware_custom: ""
photoprism_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
photoprism_role_traefik_enabled: true
photoprism_role_traefik_api_enabled: false
photoprism_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
photoprism_role_docker_container: "{{ photoprism_name }}"

# Image
photoprism_role_docker_image_pull: true
photoprism_role_docker_image_tag: "latest"
photoprism_role_docker_image: "photoprism/photoprism:{{ photoprism_role_docker_image_tag }}"

# Envs
photoprism_role_docker_envs_default:
  PHOTOPRISM_ADMIN_PASSWORD: "{{ user.pass }}"
  PHOTOPRISM_AUTH_MODE: "password"
  PHOTOPRISM_SITE_URL: "{{ photoprism_role_web_url }}"
  PHOTOPRISM_ORIGINALS_LIMIT: "5000"
  PHOTOPRISM_HTTP_COMPRESSION: "gzip"
  PHOTOPRISM_LOG_LEVEL: "info"
  PHOTOPRISM_READONLY: "false"
  PHOTOPRISM_EXPERIMENTAL: "false"
  PHOTOPRISM_DISABLE_CHOWN: "false"
  PHOTOPRISM_DISABLE_WEBDAV: "false"
  PHOTOPRISM_DISABLE_SETTINGS: "false"
  PHOTOPRISM_DISABLE_TENSORFLOW: "false"
  PHOTOPRISM_DISABLE_FACES: "false"
  PHOTOPRISM_DISABLE_CLASSIFICATION: "false"
  PHOTOPRISM_DISABLE_RAW: "false"
  PHOTOPRISM_RAW_PRESETS: "false"
  PHOTOPRISM_JPEG_QUALITY: "85"
  PHOTOPRISM_DETECT_NSFW: "false"
  PHOTOPRISM_UPLOAD_NSFW: "false"
  PHOTOPRISM_DATABASE_DRIVER: "mysql"
  PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"
  PHOTOPRISM_DATABASE_NAME: "photoprisms"
  PHOTOPRISM_DATABASE_USER: "root"
  PHOTOPRISM_DATABASE_PASSWORD: "password321"
  PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
  PHOTOPRISM_SITE_DESCRIPTION: "Trying out PhotoPrism!"
  PHOTOPRISM_SITE_AUTHOR: "{{ user.name }}"
  PHOTOPRISM_INIT: "gpu tensorflow"
photoprism_role_docker_envs_custom: {}
photoprism_role_docker_envs: "{{ photoprism_role_docker_envs_default
                            | combine(photoprism_role_docker_envs_custom) }}"

# Volumes
photoprism_role_docker_volumes_default:
  - "{{ photoprism_role_paths_location }}/originals:/photoprism/originals"
  - "{{ photoprism_role_paths_location }}/import:/photoprism/import"
  - "{{ photoprism_role_paths_location }}/storage:/photoprism/storage"
photoprism_role_docker_volumes_custom: []
photoprism_role_docker_volumes: "{{ photoprism_role_docker_volumes_default
                               + photoprism_role_docker_volumes_custom }}"

# Hostname
photoprism_role_docker_hostname: "{{ photoprism_name }}"

# Networks
photoprism_role_docker_networks_alias: "{{ photoprism_name }}"
photoprism_role_docker_networks_default: []
photoprism_role_docker_networks_custom: []
photoprism_role_docker_networks: "{{ docker_networks_common
                                + photoprism_role_docker_networks_default
                                + photoprism_role_docker_networks_custom }}"

# Security Opts
photoprism_role_docker_security_opts_default:
  - "seccomp=unconfined"
  - "apparmor=unconfined"
photoprism_role_docker_security_opts_custom: []
photoprism_role_docker_security_opts: "{{ photoprism_role_docker_security_opts_default
                                     + photoprism_role_docker_security_opts_custom }}"

# Working Directory
photoprism_role_docker_working_dir: "/photoprism"

# Restart Policy
photoprism_role_docker_restart_policy: unless-stopped

# State
photoprism_role_docker_state: started

# User
photoprism_role_docker_user: "{{ uid }}:{{ gid }}"

# Dependencies
photoprism_depends_on: "mariadb"
photoprism_depends_on_delay: "0"
photoprism_depends_on_healthchecks: "false"
