#########################################################################
# Title:            Sandbox: komga                                      #
# Author(s):        theotocopulitos, crowquill                          #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

komga_name: komga

################################
# Paths
################################

komga_role_paths_folder: "{{ komga_name }}"
komga_role_paths_location: "{{ server_appdata_path }}/{{ komga_role_paths_folder }}"
komga_role_paths_folders_list:
  - "{{ komga_role_paths_location }}"
  - "/mnt/local/Media/Comics"

################################
# Web
################################

komga_role_web_subdomain: "{{ komga_name }}"
komga_role_web_domain: "{{ user.domain }}"
komga_role_web_port: "25600"
komga_role_web_url: "{{ 'https://' + (komga_role_web_subdomain + '.' + komga_role_web_domain
                if (komga_role_web_subdomain | length > 0)
                else komga_role_web_domain) }}"

################################
# DNS
################################

komga_role_dns_record: "{{ komga_role_web_subdomain }}"
komga_role_dns_zone: "{{ komga_role_web_domain }}"
komga_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

komga_role_traefik_sso_middleware: ""
komga_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
komga_role_traefik_middleware_custom: ""
komga_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
komga_role_traefik_enabled: true
komga_role_traefik_api_enabled: false
komga_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
komga_role_docker_container: "{{ komga_name }}"

# Image
komga_role_docker_image_pull: true
komga_role_docker_image_tag: "latest"
komga_role_docker_image: "gotson/komga:{{ komga_role_docker_image_tag }}"

# Volumes
komga_role_docker_volumes_default:
  - "{{ komga_role_paths_location }}:/config"
  - "/mnt/unionfs/Media/Comics:/comics"
komga_role_docker_volumes_custom: []
komga_role_docker_volumes: "{{ komga_role_docker_volumes_default
                          + komga_role_docker_volumes_custom }}"

# Hostname
komga_role_docker_hostname: "{{ komga_name }}"

# Networks
komga_role_docker_networks_alias: "{{ komga_name }}"
komga_role_docker_networks_default: []
komga_role_docker_networks_custom: []
komga_role_docker_networks: "{{ docker_networks_common
                           + komga_role_docker_networks_default
                           + komga_role_docker_networks_custom }}"

# Restart Policy
komga_role_docker_restart_policy: unless-stopped

# State
komga_role_docker_state: started

# User
komga_role_docker_user: "{{ uid }}:{{ gid }}"
