##########################################################################
# Title:         Sandbox: Barcode Buddy | Default Variables              #
# Author(s):     edzeg                                                   #
# URL:           https://github.com/Forceu/barcodebuddy                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

barcodebuddy_name: barcodebuddy

################################
# Paths
################################

barcodebuddy_role_paths_folder: "{{ barcodebuddy_name }}"
barcodebuddy_role_paths_location: "{{ server_appdata_path }}/{{ barcodebuddy_role_paths_folder }}"
barcodebuddy_role_paths_folders_list:
  - "{{ barcodebuddy_role_paths_location }}"

################################
# Web
################################

barcodebuddy_role_web_subdomain: "{{ barcodebuddy_name }}"
barcodebuddy_role_web_domain: "{{ user.domain }}"
barcodebuddy_role_web_port: "80"
barcodebuddy_role_web_url: "{{ 'https://' + (barcodebuddy_role_web_subdomain + '.' + barcodebuddy_role_web_domain
                       if (barcodebuddy_role_web_subdomain | length > 0)
                       else barcodebuddy_role_web_domain) }}"

################################
# DNS
################################

barcodebuddy_role_dns_record: "{{ barcodebuddy_role_web_subdomain }}"
barcodebuddy_role_dns_zone: "{{ barcodebuddy_role_web_domain }}"
barcodebuddy_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

barcodebuddy_role_traefik_sso_middleware: ""
barcodebuddy_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
barcodebuddy_role_traefik_middleware_custom: ""
barcodebuddy_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
barcodebuddy_role_traefik_enabled: true

################################
# Docker
################################

# Container
barcodebuddy_role_docker_container: "{{ barcodebuddy_name }}"

# Image
barcodebuddy_role_docker_image_pull: true
barcodebuddy_role_docker_image_tag: "latest"
barcodebuddy_role_docker_image: "f0rc3/barcodebuddy:{{ barcodebuddy_role_docker_image_tag }}"

# Envs
barcodebuddy_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
barcodebuddy_role_docker_envs_custom: {}
barcodebuddy_role_docker_envs: "{{ barcodebuddy_role_docker_envs_default
                              | combine(barcodebuddy_role_docker_envs_custom) }}"

# Volumes
barcodebuddy_role_docker_volumes_default:
  - "{{ barcodebuddy_role_paths_location }}:/config"
barcodebuddy_role_docker_volumes_custom: []
barcodebuddy_role_docker_volumes: "{{ barcodebuddy_role_docker_volumes_default
                                 + barcodebuddy_role_docker_volumes_custom }}"

# Hostname
barcodebuddy_role_docker_hostname: "{{ barcodebuddy_name }}"

# Networks
barcodebuddy_role_docker_networks_alias: "{{ barcodebuddy_name }}"
barcodebuddy_role_docker_networks_default: []
barcodebuddy_role_docker_networks_custom: []
barcodebuddy_role_docker_networks: "{{ docker_networks_common
                                  + barcodebuddy_role_docker_networks_default
                                  + barcodebuddy_role_docker_networks_custom }}"

# Restart Policy
barcodebuddy_role_docker_restart_policy: unless-stopped

# State
barcodebuddy_role_docker_state: started
