#########################################################################
# Title:            Sandbox: Immich                                     #
# Author(s):        CHAIR/Raneydazed                                    #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Remove legacy redis Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"
  vars:
    var_prefix: "{{ immich_name }}_redis"

- name: Import Redis Role
  ansible.builtin.include_role:
    name: redis
  vars:
    redis_instances: ["{{ immich_name }}-redis"]
    redis_role_docker_image_tag: "8-alpine"
    redis_role_paths_folder: "{{ immich_name }}"
    redis_role_paths_location: "{{ server_appdata_path }}/{{ redis_role_paths_folder }}/redis"

- name: Remove legacy PostgreSQL Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"
  vars:
    var_prefix: "{{ immich_name }}_postgres"

- name: Import PostgreSQL Role
  ansible.builtin.include_role:
    name: postgres
  vars:
    postgres_instances: ["{{ immich_postgres_name }}"]
    postgres_role_docker_env_db: "{{ immich_postgres_role_docker_env_db }}"
    postgres_role_docker_image_tag: "{{ immich_postgres_role_docker_image_tag }}"
    postgres_role_docker_image_repo: "{{ immich_postgres_role_docker_image_repo }}"
    postgres_role_docker_shm_size: "{{ immich_postgres_role_docker_shm_size }}"
    postgres_role_paths_folder: "{{ immich_postgres_role_paths_folder }}"
    postgres_role_paths_location: "{{ immich_postgres_role_paths_location }}"
    postgres_role_docker_envs_custom: "{{ immich_postgres_role_docker_envs_custom }}"

- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('role_var', '_dns_record') }}"
    dns_zone: "{{ lookup('role_var', '_dns_zone') }}"
    dns_proxy: "{{ lookup('role_var', '_dns_proxy') }}"

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Docker Devices Task
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/set_docker_devices_variable.yml"
  when: gpu.intel or use_nvidia

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
