#########################################################################
# Title:         Sandbox: Transmission | Post-Install Tasks             #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Post-Install | Wait for config files to be created
  ansible.builtin.wait_for:
    path: "{{ transmission_role_paths_setttings_location }}"
    state: present

- name: Post-Install | Wait for 10 seconds
  ansible.builtin.wait_for:
    timeout: 10

- name: Stop Docker Container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/stop_docker_container.yml"

- name: Post-Install | Settings Task
  ansible.builtin.import_tasks: "settings/main.yml"

- name: Start Docker Container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/start_docker_container.yml"
