##########################################################################
# Title:         Sandbox: Private Bin | Default Variables                #
# Author(s):     tipdec-siblyn, thatsnasty, salty                        #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

privatebin_name: privatebin

################################
# Paths
################################

privatebin_role_paths_folder: "{{ privatebin_name }}"
privatebin_role_paths_location: "{{ server_appdata_path }}/{{ privatebin_role_paths_folder }}"
privatebin_role_paths_folders_list:
  - "{{ privatebin_role_paths_location }}"

################################
# Web
################################

privatebin_role_web_subdomain: "{{ privatebin_name }}"
privatebin_role_web_domain: "{{ user.domain }}"
privatebin_role_web_port: "8080"
privatebin_role_web_url: "{{ 'https://' + (privatebin_role_web_subdomain + '.' + privatebin_role_web_domain
                     if (privatebin_role_web_subdomain | length > 0)
                     else privatebin_role_web_domain) }}"

################################
# DNS
################################

privatebin_role_dns_record: "{{ privatebin_role_web_subdomain }}"
privatebin_role_dns_zone: "{{ privatebin_role_web_domain }}"
privatebin_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

privatebin_role_traefik_sso_middleware: ""
privatebin_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
privatebin_role_traefik_middleware_custom: ""
privatebin_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
privatebin_role_traefik_enabled: true
privatebin_role_traefik_api_enabled: false
privatebin_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
privatebin_role_docker_container: "{{ privatebin_name }}"

# Image
privatebin_role_docker_image_pull: true
privatebin_role_docker_image_tag: "latest"
privatebin_role_docker_image: "privatebin/nginx-fpm-alpine:{{ privatebin_role_docker_image_tag }}"

# Envs
privatebin_role_docker_envs_default:
  TZ: "{{ tz }}"
  PHP_TZ: "{{ tz }}"
privatebin_role_docker_envs_custom: {}
privatebin_role_docker_envs: "{{ privatebin_role_docker_envs_default
                            | combine(privatebin_role_docker_envs_custom) }}"

# Volumes
privatebin_role_docker_volumes_default:
  - "{{ privatebin_role_paths_location }}:/srv/data"
  - "{{ privatebin_role_paths_location }}/conf.php:/srv/cfg/conf.php:ro"
  - "{{ privatebin_name }}_tmpfs_run:/run"
privatebin_role_docker_volumes_custom: []
privatebin_role_docker_volumes: "{{ privatebin_role_docker_volumes_default
                               + privatebin_role_docker_volumes_custom }}"

# Mounts
privatebin_role_docker_mounts_default:
  - target: /tmp
    type: tmpfs
  - target: /var/lib/nginx/tmp
    type: tmpfs
privatebin_role_docker_mounts_custom: []
privatebin_role_docker_mounts: "{{ privatebin_role_docker_mounts_default
                              + privatebin_role_docker_mounts_custom }}"

# Hostname
privatebin_role_docker_hostname: "{{ privatebin_name }}"

# Networks
privatebin_role_docker_networks_alias: "{{ privatebin_name }}"
privatebin_role_docker_networks_default: []
privatebin_role_docker_networks_custom: []
privatebin_role_docker_networks: "{{ docker_networks_common
                                + privatebin_role_docker_networks_default
                                + privatebin_role_docker_networks_custom }}"

# Read Only
privatebin_role_docker_read_only: true

# Restart Policy
privatebin_role_docker_restart_policy: unless-stopped

# State
privatebin_role_docker_state: started

# User
privatebin_role_docker_user: "{{ uid }}:{{ gid }}"
