##########################################################################
# Title:            Sandbox: unmanic   | Default Variables               #
# Author(s):        chazlarson, kowalski                                 #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

unmanic_name: unmanic

################################
# Paths
################################

unmanic_role_paths_folder: "{{ unmanic_name }}"
unmanic_role_paths_location: "{{ server_appdata_path }}/{{ unmanic_role_paths_folder }}"
unmanic_role_paths_transcodes_location: "{{ transcodes_path }}/{{ unmanic_role_paths_folder }}"
unmanic_role_paths_folders_list:
  - "{{ unmanic_role_paths_location }}"
  - "{{ unmanic_role_paths_transcodes_location }}"

################################
# Web
################################

unmanic_role_web_subdomain: "{{ unmanic_name }}"
unmanic_role_web_domain: "{{ user.domain }}"
unmanic_role_web_port: "8888"
unmanic_role_web_url: "{{ 'https://' + (unmanic_role_web_subdomain + '.' + unmanic_role_web_domain
                       if (unmanic_role_web_subdomain | length > 0)
                       else unmanic_role_web_domain) }}"

################################
# DNS
################################

unmanic_role_dns_record: "{{ unmanic_role_web_subdomain }}"
unmanic_role_dns_zone: "{{ unmanic_role_web_domain }}"
unmanic_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

unmanic_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
unmanic_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
unmanic_role_traefik_middleware_custom: ""
unmanic_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
unmanic_role_traefik_enabled: true
unmanic_role_traefik_api_enabled: false
unmanic_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
unmanic_role_docker_container: "{{ unmanic_name }}"

# Image
unmanic_role_docker_image_pull: true
unmanic_role_docker_image_tag: "latest"
unmanic_role_docker_image: "josh5/unmanic:{{ unmanic_role_docker_image_tag }}"

# Envs
unmanic_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
unmanic_role_docker_envs_custom: {}
unmanic_role_docker_envs: "{{ unmanic_role_docker_envs_default
                              | combine(unmanic_role_docker_envs_custom) }}"

# Volumes
unmanic_role_docker_volumes_default:
  - "{{ unmanic_role_paths_location }}:/config"
  - "{{ unmanic_role_paths_transcodes_location }}:/tmp/unmanic"
  - "/mnt/unionfs/Media:/library"
unmanic_role_docker_volumes_custom: []
unmanic_role_docker_volumes: "{{ unmanic_role_docker_volumes_default
                                 + unmanic_role_docker_volumes_custom }}"

# Hostname
unmanic_role_docker_hostname: "{{ unmanic_name }}"

# Networks
unmanic_role_docker_networks_alias: "{{ unmanic_name }}"
unmanic_role_docker_networks_default: []
unmanic_role_docker_networks_custom: []
unmanic_role_docker_networks: "{{ docker_networks_common
                                  + unmanic_role_docker_networks_default
                                  + unmanic_role_docker_networks_custom }}"

# Restart Policy
unmanic_role_docker_restart_policy: unless-stopped

# State
unmanic_role_docker_state: started
