##########################################################################
# Title:         Sandbox: Kavita | Default Variables                     #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

kavita_name: kavita

################################
# Paths
################################

kavita_role_paths_folder: "{{ kavita_name }}"
kavita_role_paths_location: "{{ server_appdata_path }}/{{ kavita_role_paths_folder }}"
kavita_role_paths_folders_list:
  - "{{ kavita_role_paths_location }}"

################################
# Web
################################

kavita_role_web_subdomain: "{{ kavita_name }}"
kavita_role_web_domain: "{{ user.domain }}"
kavita_role_web_port: "5000"
kavita_role_web_url: "{{ 'https://' + (kavita_role_web_subdomain + '.' + kavita_role_web_domain
                 if (kavita_role_web_subdomain | length > 0)
                 else kavita_role_web_domain) }}"

################################
# DNS
################################

kavita_role_dns_record: "{{ kavita_role_web_subdomain }}"
kavita_role_dns_zone: "{{ kavita_role_web_domain }}"
kavita_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

kavita_role_traefik_sso_middleware: ""
kavita_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
kavita_role_traefik_middleware_custom: ""
kavita_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
kavita_role_traefik_enabled: true
kavita_role_traefik_api_enabled: false
kavita_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
kavita_role_docker_container: "{{ kavita_name }}"

# Image
kavita_role_docker_image_pull: true
kavita_role_docker_image_tag: "latest"
kavita_role_docker_image: "jvmilazz0/kavita:{{ kavita_role_docker_image_tag }}"

# Envs
kavita_role_docker_envs_default:
  TZ: "{{ tz }}"
kavita_role_docker_envs_custom: {}
kavita_role_docker_envs: "{{ kavita_role_docker_envs_default
                        | combine(kavita_role_docker_envs_custom) }}"

# Volumes
kavita_role_docker_volumes_default:
  - "{{ kavita_role_paths_location }}:/kavita/config"
kavita_role_docker_volumes_custom: []
kavita_role_docker_volumes: "{{ kavita_role_docker_volumes_default
                           + kavita_role_docker_volumes_custom }}"

# Hostname
kavita_role_docker_hostname: "{{ kavita_name }}"

# Networks
kavita_role_docker_networks_alias: "{{ kavita_name }}"
kavita_role_docker_networks_default: []
kavita_role_docker_networks_custom: []
kavita_role_docker_networks: "{{ docker_networks_common
                            + kavita_role_docker_networks_default
                            + kavita_role_docker_networks_custom }}"

# Restart Policy
kavita_role_docker_restart_policy: unless-stopped

# State
kavita_role_docker_state: started
