##########################################################################
# Title:         Sandbox: Profilarr | Default Variables                  #
# Author(s):     keldian                                                 #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

profilarr_name: profilarr

################################
# Paths
################################

profilarr_role_paths_folder: "{{ profilarr_name }}"
profilarr_role_paths_location: "{{ server_appdata_path }}/{{ profilarr_role_paths_folder }}"
profilarr_role_paths_folders_list:
  - "{{ profilarr_role_paths_location }}"

################################
# Web
################################

profilarr_role_web_subdomain: "{{ profilarr_name }}"
profilarr_role_web_domain: "{{ user.domain }}"
profilarr_role_web_port: "6868"
profilarr_role_web_url: "{{ 'https://' + (profilarr_role_web_subdomain + '.' + profilarr_role_web_domain
                    if (profilarr_role_web_subdomain | length > 0)
                    else profilarr_role_web_domain) }}"

################################
# DNS
################################

profilarr_role_dns_record: "{{ profilarr_role_web_subdomain }}"
profilarr_role_dns_zone: "{{ profilarr_role_web_domain }}"
profilarr_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

profilarr_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
profilarr_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
profilarr_role_traefik_middleware_custom: ""
profilarr_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
profilarr_role_traefik_enabled: true
profilarr_role_traefik_api_enabled: true
profilarr_role_traefik_api_endpoint: "PathPrefix(`/api`)"

################################
# Docker
################################

# Container
profilarr_role_docker_container: "{{ profilarr_name }}"

# Image
profilarr_role_docker_image_pull: true
profilarr_role_docker_image_repo: "santiagosayshey/profilarr"
profilarr_role_docker_image_tag: "latest"
profilarr_role_docker_image: "{{ profilarr_role_docker_image_repo }}:{{ profilarr_role_docker_image_tag }}"

# Envs
profilarr_role_docker_envs_default:
  TZ: "{{ tz }}"
profilarr_role_docker_envs_custom: {}
profilarr_role_docker_envs: "{{ profilarr_role_docker_envs_default
                           | combine(profilarr_role_docker_envs_custom) }}"

# Volumes
profilarr_role_docker_volumes_default:
  - "{{ profilarr_role_paths_location }}:/config"
profilarr_role_docker_volumes_custom: []
profilarr_role_docker_volumes: "{{ profilarr_role_docker_volumes_default
                              + profilarr_role_docker_volumes_custom }}"

# Hostname
profilarr_role_docker_hostname: "{{ profilarr_name }}"

# Networks
profilarr_role_docker_networks_alias: "{{ profilarr_name }}"
profilarr_role_docker_networks_default: []
profilarr_role_docker_networks_custom: []
profilarr_role_docker_networks: "{{ docker_networks_common
                               + profilarr_role_docker_networks_default
                               + profilarr_role_docker_networks_custom }}"

# Restart Policy
profilarr_role_docker_restart_policy: unless-stopped

# State
profilarr_role_docker_state: started

# User
profilarr_role_docker_user: "{{ uid }}:{{ gid }}"
