##########################################################################
# Title:            Sandbox: Firefly-III                                 #
# Author(s):        Barrow1990                                           #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('role_var', '_dns_record') }}"
    dns_zone: "{{ lookup('role_var', '_dns_zone') }}"
    dns_proxy: "{{ lookup('role_var', '_dns_proxy') }}"

- name: "Save Fireflyiii Mariadb Password Saltbox facts"
  saltbox_facts:
    role: "fireflyiii"
    instance: "fireflyiii_db_password"
    keys:
      secret_key: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32') }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"
  register: fireflyiii_db_password_saltbox_facts

- name: "Save Fireflyiii AppKey Saltbox facts"
  saltbox_facts:
    role: "fireflyiii"
    instance: "fireflyiii_appkey"
    keys:
      secret_key: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32') }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"
  register: fireflyiii_appkey_saltbox_facts

- name: MariaDB Role
  ansible.builtin.include_role:
    name: mariadb
  vars:
    mariadb_instances: ["{{ fireflyiii_mariadb_name }}"]
    mariadb_role_paths_folder: "{{ fireflyiii_mariadb_role_paths_folder }}"
    mariadb_role_paths_location: "{{ fireflyiii_mariadb_role_paths_location }}"
    mariadb_role_docker_image_tag: "{{ fireflyiii_mariadb_role_docker_image_tag }}"
    mariadb_role_docker_env_db: "{{ fireflyiii_mariadb_role_docker_env_db }}"
    mariadb_role_docker_env_password: "{{ fireflyiii_mariadb_role_docker_env_password }}"

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
