#########################################################################
# Title:            Sandbox: File Browser                               #
# Author(s):        RXWatcher, kowalski                                 #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

filebrowser_name: filebrowser

################################
# Paths
################################

filebrowser_role_paths_folder: "{{ filebrowser_name }}"
filebrowser_role_paths_location: "{{ server_appdata_path }}/{{ filebrowser_role_paths_folder }}"
filebrowser_role_paths_folders_list:
  - "{{ filebrowser_role_paths_location }}"
  - "{{ filebrowser_role_paths_location }}/config"
  - "{{ filebrowser_role_paths_location }}/database"
filebrowser_role_paths_config_location: "{{ filebrowser_role_paths_location }}/filebrowser.json"
filebrowser_role_paths_config_folder: "{{ filebrowser_role_paths_location }}/config"
filebrowser_role_paths_db_location: "{{ filebrowser_role_paths_location }}/filebrowser.db"
filebrowser_role_paths_db_folder: "{{ filebrowser_role_paths_location }}/database"

################################
# Web
################################

filebrowser_role_web_subdomain: "{{ filebrowser_name }}"
filebrowser_role_web_domain: "{{ user.domain }}"
filebrowser_role_web_port: "80"
filebrowser_role_web_url: "{{ 'https://' + (filebrowser_role_web_subdomain + '.' + filebrowser_role_web_domain
                      if (filebrowser_role_web_subdomain | length > 0)
                      else filebrowser_role_web_domain) }}"

################################
# DNS
################################

filebrowser_role_dns_record: "{{ filebrowser_role_web_subdomain }}"
filebrowser_role_dns_zone: "{{ filebrowser_role_web_domain }}"
filebrowser_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

filebrowser_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
filebrowser_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
filebrowser_role_traefik_middleware_custom: ""
filebrowser_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
filebrowser_role_traefik_enabled: true
filebrowser_role_traefik_api_enabled: true
filebrowser_role_traefik_api_endpoint: "PathPrefix(`/api`) || PathPrefix(`/share`) || PathPrefix(`/static`) || PathPrefix(`/api/public`)"

################################
# Docker
################################

# Container
filebrowser_role_docker_container: "{{ filebrowser_name }}"

# Image
filebrowser_role_docker_image_pull: true
filebrowser_role_docker_image_tag: "latest"
filebrowser_role_docker_image: "filebrowser/filebrowser:{{ filebrowser_role_docker_image_tag }}"

# Envs
filebrowser_role_docker_envs_default:
  TZ: "{{ tz }}"
filebrowser_role_docker_envs_custom: {}
filebrowser_role_docker_envs: "{{ filebrowser_role_docker_envs_default
                             | combine(filebrowser_role_docker_envs_custom) }}"

# Volumes
filebrowser_role_docker_volumes_default:
  - "{{ filebrowser_role_paths_db_folder }}:/database"
  - "{{ filebrowser_role_paths_config_folder }}:/config"
  - "/mnt/unionfs:/srv:rslave"
filebrowser_role_docker_volumes_custom: []
filebrowser_role_docker_volumes: "{{ filebrowser_role_docker_volumes_default
                                + filebrowser_role_docker_volumes_custom }}"

# Hostname
filebrowser_role_docker_hostname: "{{ filebrowser_name }}"

# Networks
filebrowser_role_docker_networks_alias: "{{ filebrowser_name }}"
filebrowser_role_docker_networks_default: []
filebrowser_role_docker_networks_custom: []
filebrowser_role_docker_networks: "{{ docker_networks_common
                                 + filebrowser_role_docker_networks_default
                                 + filebrowser_role_docker_networks_custom }}"

# Restart Policy
filebrowser_role_docker_restart_policy: unless-stopped

# State
filebrowser_role_docker_state: started

# User
filebrowser_role_docker_user: "{{ uid }}:{{ gid }}"
