##########################################################################
# Title:         Sandbox: Deluge VPN | Default Variables                 #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

delugevpn_name: delugevpn

################################
# Settings
################################

delugevpn_log_level_daemon: info
delugevpn_log_level_web: info
delugevpn_name_servers: "84.200.69.80,1.1.1.1,84.200.70.40,1.0.0.1"
delugevpn_lan_network: "172.19.0.0/16"

################################
# Paths
################################

delugevpn_role_paths_folder: "{{ delugevpn_name }}"
delugevpn_role_paths_location: "{{ server_appdata_path }}/{{ delugevpn_role_paths_folder }}"
delugevpn_role_paths_folders_list:
  - "{{ delugevpn_role_paths_location }}"
  - "{{ delugevpn_role_paths_location }}/wireguard"
  - "{{ downloads_torrents_path }}"
  - "{{ downloads_torrents_path }}/delugevpn"
  - "{{ downloads_torrents_path }}/delugevpn/completed"
  - "{{ downloads_torrents_path }}/delugevpn/incoming"
  - "{{ downloads_torrents_path }}/delugevpn/watched"

################################
# Web
################################

delugevpn_role_web_subdomain: "{{ delugevpn_name }}"
delugevpn_role_web_domain: "{{ user.domain }}"
delugevpn_role_web_port: "8112"
delugevpn_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='delugevpn') + '.' + lookup('role_var', '_web_domain', role='delugevpn')
                         if (lookup('role_var', '_web_subdomain', role='delugevpn') | length > 0)
                         else lookup('role_var', '_web_domain', role='delugevpn')) }}"

################################
# DNS
################################

delugevpn_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='delugevpn') }}"
delugevpn_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='delugevpn') }}"
delugevpn_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

delugevpn_role_traefik_sso_middleware: ""
delugevpn_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
delugevpn_role_traefik_middleware_custom: ""
delugevpn_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
delugevpn_role_traefik_enabled: true
delugevpn_role_traefik_api_enabled: false
delugevpn_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
delugevpn_role_docker_container: "{{ delugevpn_name }}"

# Image
delugevpn_role_docker_image_pull: true
delugevpn_role_docker_image_repo: "binhex/arch-delugevpn"
delugevpn_role_docker_image_tag: "latest"
delugevpn_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='delugevpn') }}:{{ lookup('role_var', '_docker_image_tag', role='delugevpn') }}"

# Ports
delugevpn_role_docker_ports_defaults:
  - "58112:58112"
  - "58846:58846"
delugevpn_role_docker_ports_custom: []
delugevpn_role_docker_ports: "{{ lookup('role_var', '_docker_ports_defaults', role='delugevpn')
                                 + lookup('role_var', '_docker_ports_custom', role='delugevpn') }}"

# Envs
delugevpn_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  VPN_ENABLED: "yes"
  VPN_USER: "{{ delugevpn.vpn_user | default('username', true) }}"
  VPN_PASS: "{{ delugevpn.vpn_pass | default('password', true) }}"
  VPN_PROV: "{{ delugevpn.vpn_prov | default('pia', true) }}"
  VPN_CLIENT: "{{ delugevpn.vpn_client | default('wireguard', true) }}"
  STRICT_PORT_FORWARD: "yes"
  ENABLE_PRIVOXY: "no"
  LAN_NETWORK: "{{ delugevpn_lan_network }}"
  NAME_SERVERS: "{{ delugevpn_name_servers }}"
  DELUGE_DAEMON_LOG_LEVEL: "{{ delugevpn_log_level_daemon }}"
  DELUGE_WEB_LOG_LEVEL: "{{ delugevpn_log_level_web }}"
  DEBUG: "false"
  UMASK: "022"
delugevpn_role_docker_envs_custom: {}
delugevpn_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='delugevpn')
                                | combine(lookup('role_var', '_docker_envs_custom', role='delugevpn')) }}"

# Volumes
delugevpn_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='delugevpn') }}:/config"
  - "/etc/localtime:/etc/localtime:ro"
  - "/opt/scripts:/scripts"
delugevpn_role_docker_volumes_custom: []
delugevpn_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='delugevpn')
                                   + lookup('role_var', '_docker_volumes_custom', role='delugevpn') }}"

# Hostname
delugevpn_role_docker_hostname: "{{ delugevpn_name }}"

# Networks
delugevpn_role_docker_networks_alias: "{{ delugevpn_name }}"
delugevpn_role_docker_networks_default: []
delugevpn_role_docker_networks_custom: []
delugevpn_role_docker_networks: "{{ docker_networks_common
                                    + lookup('role_var', '_docker_networks_default', role='delugevpn')
                                    + lookup('role_var', '_docker_networks_custom', role='delugevpn') }}"

# Restart Policy
delugevpn_role_docker_restart_policy: unless-stopped

# State
delugevpn_role_docker_state: started

# Sysctls
delugevpn_role_docker_sysctls:
  net.ipv4.conf.all.src_valid_mark: "1"

# Privileged
delugevpn_role_docker_privileged: true
