##########################################################################
# Title:         Sandbox: Mylar3 | Default Variables                     #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

mylar3_name: mylar3

################################
# Paths
################################

mylar3_role_paths_folder: "{{ mylar3_name }}"
mylar3_role_paths_location: "{{ server_appdata_path }}/{{ mylar3_role_paths_folder }}"
mylar3_role_paths_folders_list:
  - "{{ mylar3_role_paths_location }}"
  - /mnt/local/Media/Comics

################################
# Web
################################

mylar3_role_web_subdomain: "{{ mylar3_name }}"
mylar3_role_web_domain: "{{ user.domain }}"
mylar3_role_web_port: "8090"
mylar3_role_web_url: "{{ 'https://' + (mylar3_role_web_subdomain + '.' + mylar3_role_web_domain
                 if (mylar3_role_web_subdomain | length > 0)
                 else mylar3_role_web_domain) }}"

################################
# DNS
################################

mylar3_role_dns_record: "{{ mylar3_role_web_subdomain }}"
mylar3_role_dns_zone: "{{ mylar3_role_web_domain }}"
mylar3_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

mylar3_role_traefik_sso_middleware: ""
mylar3_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
mylar3_role_traefik_middleware_custom: ""
mylar3_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
mylar3_role_traefik_enabled: true
mylar3_role_traefik_api_enabled: false
mylar3_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
mylar3_role_docker_container: "{{ mylar3_name }}"

# Image
mylar3_role_docker_image_pull: true
mylar3_role_docker_image_tag: "latest"
mylar3_role_docker_image: "lscr.io/linuxserver/mylar3:{{ mylar3_role_docker_image_tag }}"

# Envs
mylar3_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
mylar3_role_docker_envs_custom: {}
mylar3_role_docker_envs: "{{ mylar3_role_docker_envs_default
                        | combine(mylar3_role_docker_envs_custom) }}"

# Volumes
mylar3_role_docker_volumes_default:
  - "{{ mylar3_role_paths_location }}:/config"
  - "/mnt/unionfs/Media/Comics:/comics"
mylar3_role_docker_volumes_custom: []
mylar3_role_docker_volumes: "{{ mylar3_role_docker_volumes_default
                           + mylar3_role_docker_volumes_custom }}"

# Hostname
mylar3_role_docker_hostname: "{{ mylar3_name }}"

# Networks
mylar3_role_docker_networks_alias: "{{ mylar3_name }}"
mylar3_role_docker_networks_default: []
mylar3_role_docker_networks_custom: []
mylar3_role_docker_networks: "{{ docker_networks_common
                            + mylar3_role_docker_networks_default
                            + mylar3_role_docker_networks_custom }}"

# Restart Policy
mylar3_role_docker_restart_policy: unless-stopped

# State
mylar3_role_docker_state: started
