##########################################################################
# Title:         Sandbox: Dopplarr | Default Variables                   #
# Author(s):     Grostim                                                 #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

doplarr_name: doplarr

################################
# Docker
################################

# Container
doplarr_role_docker_container: "{{ doplarr_name }}"

# Image
doplarr_role_docker_image_pull: true
doplarr_role_docker_image_tag: "latest"
doplarr_role_docker_image: "lscr.io/linuxserver/doplarr:{{ doplarr_role_docker_image_tag }}"

# Envs
doplarr_role_docker_envs_default:
  TZ: "{{ tz }}"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  DISCORD__TOKEN: "{{ doplarr.discord_token }}"
  OVERSEERR__URL: "{{ doplarr.overseerr_url | default('', true) }}"
  OVERSEERR__API: "{{ doplarr.overseerr_api }}"
  RADARR__API: "{{ doplarr.radarr_api | default('', true) }}"
  RADARR__URL: "{{ doplarr.radarr_url | default('', true) }}"
  SONARR__API: "{{ doplarr.sonarr_api | default('', true) }}"
  SONARR__URL: "{{ doplarr.sonarr_url | default('', true) }}"
  DISCORD__MAX_RESULTS: "{{ doplarr.discord_max_results | default('25', true) }}"
  DISCORD__ROLE_ID: "{{ doplarr.discord_role_id | default('', true) }}"
  DISCORD__REQUESTED_MSG_STYLE: "{{ doplarr.discord_requested_msg_style | default(':plain', true) }}"
  SONARR__QUALITY_PROFILE: "{{ doplarr.sonarr_quality_profile | default('', true) }}"
  RADARR__QUALITY_PROFILE: "{{ doplarr.radarr_quality_profile | default('', true) }}"
  SONARR__LANGUAGE_PROFILE: "{{ doplarr.sonarr_language_profile | default('', true) }}"
  OVERSEERR__DEFAULT_ID: "{{ doplarr.overseer_default_id | default('', true) }}"
  PARTIAL_SEASONS: "{{ doplarr.partial_seasons | default('true', true) }}"
  LOG_LEVEL: "{{ doplarr.log_level | default(':info', true) }}"
doplarr_role_docker_envs_custom: []
doplarr_role_docker_envs: "{{ doplarr_role_docker_envs_default
                         | combine(doplarr_role_docker_envs_custom) }}"

# Hostname
doplarr_role_docker_hostname: "{{ doplarr_name }}"

# Networks
doplarr_role_docker_networks_alias: "{{ doplarr_name }}"
doplarr_role_docker_networks_default: []
doplarr_role_docker_networks_custom: []
doplarr_role_docker_networks: "{{ docker_networks_common
                             + doplarr_role_docker_networks_default
                             + doplarr_role_docker_networks_custom }}"

# Restart Policy
doplarr_role_docker_restart_policy: unless-stopped

# State
doplarr_role_docker_state: started
