##########################################################################
# Title:            Sandbox: Membarr | Default Variables                 #
# Author(s):        CHAIR/Raneydazed                                     #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

membarr_name: membarr

################################
# Paths
################################

membarr_role_paths_folder: "{{ membarr_name }}"
membarr_role_paths_location: "{{ server_appdata_path }}/{{ membarr_role_paths_folder }}"
membarr_role_paths_recursive: true
membarr_role_paths_config_location: "{{ membarr_role_paths_location }}/config.ini"
membarr_role_paths_folders_list:
  - "{{ membarr_role_paths_location }}"

################################
# Docker
################################

# Container
membarr_role_docker_container: "{{ membarr_name }}"

# Image
membarr_role_docker_image_pull: true
membarr_role_docker_image_tag: "latest"
membarr_role_docker_image: "yoruio/membarr:{{ membarr_role_docker_image_tag }}"

# Envs
membarr_role_docker_envs_default:
  TZ: "{{ tz }}"
  token: "{{ membarr.discord_token }}"
membarr_role_docker_envs_custom: {}
membarr_role_docker_envs: "{{ membarr_role_docker_envs_default
                         | combine(membarr_role_docker_envs_custom) }}"

# Volumes
membarr_role_docker_volumes_default:
  - "{{ membarr_role_paths_location }}:/app/app/config"
membarr_role_docker_volumes_custom: []
membarr_role_docker_volumes: "{{ membarr_role_docker_volumes_default
                            + membarr_role_docker_volumes_custom }}"

# Hostname
membarr_role_docker_hostname: "{{ membarr_name }}"

# Networks
membarr_role_docker_networks_alias: "{{ membarr_name }}"
membarr_role_docker_networks_default: []
membarr_role_docker_networks_custom: []
membarr_role_docker_networks: "{{ docker_networks_common
                             + membarr_role_docker_networks_default
                             + membarr_role_docker_networks_custom }}"

# Restart Policy
membarr_role_docker_restart_policy: always

# State
membarr_role_docker_state: started

# User
membarr_role_docker_user: "{{ uid }}:{{ gid }}"
