##########################################################################
# Title:         Sandbox: LinkWarden | Default Variables                 #
# Author(s):     CHAIR/Raneydazed                                        #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

linkwarden_name: linkwarden

################################
# Settings
################################

linkwarden_postgres_name: "{{ linkwarden_name }}-postgres"
linkwarden_postgres_role_docker_env_user: "{{ linkwarden_name }}"
linkwarden_postgres_role_docker_env_password: "{{ linkwarden_name }}"
linkwarden_postgres_role_docker_env_db: "{{ linkwarden_name }}"
linkwarden_postgres_role_docker_image_tag: "16-alpine"
linkwarden_postgres_role_docker_image_repo: "postgres"
linkwarden_postgres_role_paths_folder: "{{ linkwarden_name }}"
linkwarden_postgres_role_paths_location: "{{ server_appdata_path }}/{{ postgres_role_paths_folder }}/postgres"

################################
# Paths
################################

linkwarden_role_paths_folder: "{{ linkwarden_name }}"
linkwarden_role_paths_location: "{{ server_appdata_path }}/{{ linkwarden_role_paths_folder }}"
linkwarden_role_paths_folders_list:
  - "{{ linkwarden_role_paths_location }}"

################################
# Web
################################

linkwarden_role_web_subdomain: "{{ linkwarden_name }}"
linkwarden_role_web_domain: "{{ user.domain }}"
linkwarden_role_web_port: "3000"
linkwarden_role_web_url: "{{ 'https://' + (linkwarden_role_web_subdomain + '.' + linkwarden_role_web_domain
                     if (linkwarden_role_web_subdomain | length > 0)
                     else linkwarden_role_web_domain) }}"

################################
# DNS
################################

linkwarden_role_dns_record: "{{ linkwarden_role_web_subdomain }}"
linkwarden_role_dns_zone: "{{ linkwarden_role_web_domain }}"
linkwarden_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

linkwarden_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
linkwarden_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
linkwarden_role_traefik_middleware_custom: ""
linkwarden_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
linkwarden_role_traefik_enabled: true
linkwarden_role_traefik_api_enabled: true
linkwarden_role_traefik_api_endpoint: "PathPrefix(`/api`)"

################################
# Docker
################################

# Container
linkwarden_role_docker_container: "{{ linkwarden_name }}"

# Image
linkwarden_role_docker_image_pull: true
linkwarden_role_docker_image_tag: "latest"
linkwarden_role_docker_image: "ghcr.io/linkwarden/linkwarden:{{ linkwarden_role_docker_image_tag }}"

# Envs
linkwarden_role_docker_envs_default:
  TZ: "{{ tz }}"
  NEXT_PUBLIC_CREDENTIALS_ENABLED: "true"
  STORAGE_FOLDER: "/data"
  NEXTAUTH_SECRET: "{{ linkwarden_secret_key.stdout }}"
  NEXTAUTH_URL: "{{ linkwarden_role_web_url }}/api/v1/auth"
  DATABASE_URL: "postgresql://{{ linkwarden_postgres_role_docker_env_user }}:{{ linkwarden_postgres_role_docker_env_password }}@{{ linkwarden_postgres_name }}:5432/{{ linkwarden_postgres_role_docker_env_db }}"
linkwarden_role_docker_envs_custom: {}
linkwarden_role_docker_envs: "{{ linkwarden_role_docker_envs_default
                            | combine(linkwarden_role_docker_envs_custom) }}"

# Volumes
linkwarden_role_docker_volumes_default:
  - "{{ linkwarden_role_paths_location }}:/data/data"
linkwarden_role_docker_volumes_custom: []
linkwarden_role_docker_volumes: "{{ linkwarden_role_docker_volumes_default
                               + linkwarden_role_docker_volumes_custom }}"

# Hostname
linkwarden_role_docker_hostname: "{{ linkwarden_name }}"

# Networks
linkwarden_role_docker_networks_alias: "{{ linkwarden_name }}"
linkwarden_role_docker_networks_default: []
linkwarden_role_docker_networks_custom: []
linkwarden_role_docker_networks: "{{ docker_networks_common
                                + linkwarden_role_docker_networks_default
                                + linkwarden_role_docker_networks_custom }}"

# Restart Policy
linkwarden_role_docker_restart_policy: unless-stopped

# State
linkwarden_role_docker_state: started

# Dependencies
linkwarden_depends_on: "{{ linkwarden_postgres_name }}"
linkwarden_depends_on_delay: "0"
linkwarden_depends_on_healthchecks: "false"
