##########################################################################
# Title:            Sandbox: Guacamole                                   #
# Author(s):        RXWatcher, kowalski                                  #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Settings
################################

guacamole_totp_enable: false
guacamole_ldap_enable: false
guacamole_radius_enable: false
guacamole_duo_enable: false
guacamole_cas_enable: false
guacamole_openid_enable: false
guacamole_saml_enable: false
guacamole_header_enable: false

################################
# Basics
################################

guacamole_name: guacamole

################################
# Paths
################################

guacamole_role_paths_folder: "{{ guacamole_name }}"
guacamole_role_paths_location: "{{ server_appdata_path }}/{{ guacamole_role_paths_folder }}"
guacamole_role_paths_folders_list:
  - "{{ guacamole_role_paths_location }}"
  - "{{ guacamole_role_paths_location }}/config"

################################
# Web
################################

guacamole_role_web_subdomain: "{{ guacamole_name }}"
guacamole_role_web_domain: "{{ user.domain }}"
guacamole_role_web_port: "8080"
guacamole_role_web_url: "{{ 'https://' + (guacamole_role_web_subdomain + '.' + guacamole_role_web_domain
                    if (guacamole_role_web_subdomain | length > 0)
                    else guacamole_role_web_domain) }}"

################################
# DNS
################################

guacamole_role_dns_record: "{{ guacamole_role_web_subdomain }}"
guacamole_role_dns_zone: "{{ guacamole_role_web_domain }}"
guacamole_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

guacamole_role_traefik_sso_middleware: ""
guacamole_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
guacamole_role_traefik_middleware_custom: ""
guacamole_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
guacamole_role_traefik_enabled: true
guacamole_role_traefik_api_enabled: false
guacamole_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
guacamole_role_docker_container: "{{ guacamole_name }}"

# Image
guacamole_role_docker_image_pull: true
guacamole_role_docker_image_tag: "latest"
guacamole_role_docker_image: "jasonbean/guacamole:{{ guacamole_role_docker_image_tag }}"

# Envs
guacamole_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  OPT_MYSQL: "Y"
  OPT_TOTP: "{{ 'Y' if guacamole_totp_enable else omit }}"
  OPT_LDAP: "{{ 'Y' if guacamole_ldap_enable else omit }}"
  OPT_RADIUS: "{{ 'Y' if guacamole_radius_enable else omit }}"
  OPT_DUO: "{{ 'Y' if guacamole_duo_enable else omit }}"
  OPT_CAS: "{{ 'Y' if guacamole_cas_enable else omit }}"
  OPT_OPENID: "{{ 'Y' if guacamole_openid_enable else omit }}"
  OPT_SAML: "{{ 'Y' if guacamole_saml_enable else omit }}"
  OPT_HEADER: "{{ 'Y' if guacamole_header_enable else omit }}"
guacamole_role_docker_envs_custom: {}
guacamole_role_docker_envs: "{{ guacamole_role_docker_envs_default
                           | combine(guacamole_role_docker_envs_custom) }}"

# Volumes
guacamole_role_docker_volumes_default:
  - "{{ guacamole_role_paths_location }}/config:/config"
guacamole_role_docker_volumes_custom: []
guacamole_role_docker_volumes: "{{ guacamole_role_docker_volumes_default
                              + guacamole_role_docker_volumes_custom }}"

# Hostname
guacamole_role_docker_hostname: "{{ guacamole_name }}"

# Networks
guacamole_role_docker_networks_alias: "{{ guacamole_name }}"
guacamole_role_docker_networks_default: []
guacamole_role_docker_networks_custom: []
guacamole_role_docker_networks: "{{ docker_networks_common
                               + guacamole_role_docker_networks_default
                               + guacamole_role_docker_networks_custom }}"

# Restart Policy
guacamole_role_docker_restart_policy: unless-stopped

# State
guacamole_role_docker_state: started
