##########################################################################
# Title:         Sandbox: Dashy | Default Variables                      #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

dashy_name: dashy

################################
# Paths
################################

dashy_role_paths_folder: "{{ dashy_name }}"
dashy_role_paths_location: "{{ server_appdata_path }}/{{ dashy_role_paths_folder }}"
dashy_role_paths_folders_list:
  - "{{ dashy_role_paths_location }}"
dashy_role_paths_config_location: "{{ dashy_role_paths_location }}/conf.yml"

################################
# Web
################################

dashy_role_web_subdomain: "{{ dashy_name }}"
dashy_role_web_domain: "{{ user.domain }}"
dashy_role_web_port: "8080"
dashy_role_web_url: "{{ 'https://' + (dashy_role_web_subdomain + '.' + dashy_role_web_domain
                if (dashy_role_web_subdomain | length > 0)
                else dashy_role_web_domain) }}"

################################
# DNS
################################

dashy_role_dns_record: "{{ dashy_role_web_subdomain }}"
dashy_role_dns_zone: "{{ dashy_role_web_domain }}"
dashy_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

dashy_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
dashy_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
dashy_role_traefik_middleware_custom: ""
dashy_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
dashy_role_traefik_enabled: true
dashy_role_traefik_api_enabled: false
dashy_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
dashy_role_docker_container: "{{ dashy_name }}"

# Image
dashy_role_docker_image_pull: true
dashy_role_docker_image_tag: "latest"
dashy_role_docker_image: "lissy93/dashy:{{ dashy_role_docker_image_tag }}"

# Volumes
dashy_role_docker_volumes_default:
  - "{{ dashy_role_paths_location }}:/app/user-data"
dashy_role_docker_volumes_custom: []
dashy_role_docker_volumes: "{{ dashy_role_docker_volumes_default
                          + dashy_role_docker_volumes_custom }}"

# Hostname
dashy_role_docker_hostname: "{{ dashy_name }}"

# Networks
dashy_role_docker_networks_alias: "{{ dashy_name }}"
dashy_role_docker_networks_default: []
dashy_role_docker_networks_custom: []
dashy_role_docker_networks: "{{ docker_networks_common
                           + dashy_role_docker_networks_default
                           + dashy_role_docker_networks_custom }}"

# Restart Policy
dashy_role_docker_restart_policy: unless-stopped

# State
dashy_role_docker_state: started

# Healthcheck
dashy_role_docker_healthcheck:
  test: ["CMD", "yarn", "health-check"]
  interval: 10s
  timeout: 5s
  retries: 10
  start_period: 10s
