#########################################################################
# Title:            Sandbox: Doplarr                                    #
# Author(s):        Grostim                                             #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Check for required variables
  ansible.builtin.fail:
    msg: "You need to set doplarr_role_discord_token, doplarr_role_overseerr_url, doplarr_role_overseerr_api, doplarr_role_radarr_api, doplarr_role_radarr_url, doplarr_role_sonarr_api, doplarr_role_sonarr_url, and doplarr_role_discord_role_id using the inventory."
  when: (not continuous_integration) and
        ((doplarr_role_discord_token | length == 0) or
         (doplarr_role_overseerr_url | length == 0) or
         (doplarr_role_overseerr_api | length == 0) or
         (doplarr_role_radarr_api | length == 0) or
         (doplarr_role_radarr_url | length == 0) or
         (doplarr_role_sonarr_api | length == 0) or
         (doplarr_role_sonarr_url | length == 0) or
         (doplarr_role_discord_role_id | length == 0))

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
