##########################################################################
# Title:            Sandbox: ZNC | Default Variables                     #
# Author(s):        kowalski                                             #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

znc_name: znc

################################
# Paths
################################

znc_role_paths_folder: "{{ znc_name }}"
znc_role_paths_location: "{{ server_appdata_path }}/{{ znc_role_paths_folder }}"
znc_role_paths_folders_list:
  - "{{ znc_role_paths_location }}"

################################
# Web
################################

znc_role_web_subdomain: "{{ znc_name }}"
znc_role_web_domain: "{{ user.domain }}"
znc_role_web_port: "6501"
znc_role_web_url: "{{ 'https://' + (znc_role_web_subdomain + '.' + znc_role_web_domain
                   if (znc_role_web_subdomain | length > 0)
                   else znc_role_web_domain) }}"

################################
# DNS
################################

znc_role_dns_record: "{{ znc_role_web_subdomain }}"
znc_role_dns_zone: "{{ znc_role_web_domain }}"
znc_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

znc_role_traefik_sso_middleware: ""
znc_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
znc_role_traefik_middleware_custom: ""
znc_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
znc_role_traefik_enabled: true
znc_role_traefik_api_enabled: false
znc_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
znc_role_docker_container: "{{ znc_name }}"

# Image
znc_role_docker_image_pull: true
znc_role_docker_image_tag: "latest"
znc_role_docker_image: "lscr.io/linuxserver/znc:{{ znc_role_docker_image_tag }}"

# Ports
znc_role_docker_ports_defaults:
  - "{{ znc_role_web_port }}:{{ znc_role_web_port }}"
  - "6502:6502"
znc_role_docker_ports_custom: []
znc_role_docker_ports: "{{ znc_role_docker_ports_defaults
                           + znc_role_docker_ports_custom }}"

# Envs
znc_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
znc_role_docker_envs_custom: {}
znc_role_docker_envs: "{{ znc_role_docker_envs_default
                          | combine(znc_role_docker_envs_custom) }}"

# Volumes
znc_role_docker_volumes_default:
  - "{{ znc_role_paths_location }}:/config"
znc_role_docker_volumes_custom: []
znc_role_docker_volumes: "{{ znc_role_docker_volumes_default
                             + znc_role_docker_volumes_custom }}"

# Hostname
znc_role_docker_hostname: "{{ znc_name }}"

# Networks
znc_role_docker_networks_alias: "{{ znc_name }}"
znc_role_docker_networks_default: []
znc_role_docker_networks_custom: []
znc_role_docker_networks: "{{ docker_networks_common
                              + znc_role_docker_networks_default
                              + znc_role_docker_networks_custom }}"

# Restart Policy
znc_role_docker_restart_policy: unless-stopped

# State
znc_role_docker_state: started
