---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Saltbox:
    - Core Repository:
        - abbr: GH
          # icon: github.png
          href: https://github.com/r3dlobst3r/Saltbox
    - Sandbox Repository:
        - abbr: GH
          # icon: github.png
          href: https://github.com/r3dlobst3r/Sandbox
    - Sandpit Repository:
        - abbr: GH
          # icon: github.png
          href: https://github.com/r3dlobst3r/Sandpit
    - Saltbox Docs:
        - abbr: DC
          # icon: github.png
          href: https://docs.saltbox.dev/
- Misc:
    - /r/selfhosted:
        - abbr: RE
          # icon: reddit.png
          href: https://www.reddit.com/r/selfhosted/
