##########################################################################
# Title:            Sandbox: Wireguard | Default Variables               #
# Author(s):        owine                                                #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

wireguard_name: wireguard

################################
# Settings
################################

wireguard_listen_port: "51820"

################################
# Paths
################################

wireguard_role_paths_folder: "{{ wireguard_name }}"
wireguard_role_paths_location: "{{ server_appdata_path }}/{{ wireguard_role_paths_folder }}"
wireguard_role_paths_folders_list:
  - "{{ wireguard_role_paths_location }}"

################################
# Web
################################

wireguard_role_web_subdomain: "{{ wireguard_name }}"
wireguard_role_web_domain: "{{ user.domain }}"
wireguard_role_web_port: "51821"
wireguard_role_web_url: "{{ 'https://' + (wireguard_role_web_subdomain + '.' + wireguard_role_web_domain
                         if (wireguard_role_web_subdomain | length > 0)
                         else wireguard_role_web_domain) }}"

################################
# DNS
################################

wireguard_role_dns_record: "{{ wireguard_role_web_subdomain }}"
wireguard_role_dns_zone: "{{ wireguard_role_web_domain }}"
wireguard_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

wireguard_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
wireguard_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
wireguard_role_traefik_middleware_custom: ""
wireguard_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
wireguard_role_traefik_enabled: true
wireguard_role_traefik_api_enabled: false
wireguard_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
wireguard_role_docker_container: "{{ wireguard_name }}"

# Image
wireguard_role_docker_image_pull: true
wireguard_role_docker_image_tag: "14"
wireguard_role_docker_image: "ghcr.io/wg-easy/wg-easy:{{ wireguard_role_docker_image_tag }}"

# Ports
wireguard_role_docker_ports_defaults:
  - "{{ wireguard_listen_port }}:51820/udp"
wireguard_role_docker_ports_custom: []
wireguard_role_docker_ports: "{{ wireguard_role_docker_ports_defaults
                                 + wireguard_role_docker_ports_custom }}"

# Envs
wireguard_role_docker_envs_default:
  TZ: "{{ tz }}"
  WG_HOST: "{{ ip_address_public }}"
  PASSWORD_HASH: "{{ user.pass | password_hash('bcrypt') }}"
  WG_PORT: "{{ wireguard_listen_port }}"
wireguard_role_docker_envs_custom: {}
wireguard_role_docker_envs: "{{ wireguard_role_docker_envs_default
                                | combine(wireguard_role_docker_envs_custom) }}"

# Volumes
wireguard_role_docker_volumes_default:
  - "{{ wireguard_role_paths_location }}:/etc/wireguard"
wireguard_role_docker_volumes_custom: []
wireguard_role_docker_volumes: "{{ wireguard_role_docker_volumes_default
                                   + wireguard_role_docker_volumes_custom }}"

# Hostname
wireguard_role_docker_hostname: "{{ wireguard_name }}"

# Networks
wireguard_role_docker_networks_alias: "{{ wireguard_name }}"
wireguard_role_docker_networks_default: []
wireguard_role_docker_networks_custom: []
wireguard_role_docker_networks: "{{ docker_networks_common
                                    + wireguard_role_docker_networks_default
                                    + wireguard_role_docker_networks_custom }}"

# Capabilities
wireguard_role_docker_capabilities_default:
  - NET_ADMIN
  - SYS_MODULE
wireguard_role_docker_capabilities_custom: []
wireguard_role_docker_capabilities: "{{ wireguard_role_docker_capabilities_default
                                        + wireguard_role_docker_capabilities_custom }}"

# Sysctls
wireguard_role_docker_sysctls:
  net.ipv4.conf.all.src_valid_mark: "1"
  net.ipv4.ip_forward: "1"

# Restart Policy
wireguard_role_docker_restart_policy: unless-stopped

# State
wireguard_role_docker_state: started
