##########################################################################
# Title:            Sandbox: Heimdall | Default Variables                #
# Author(s):        TheBradz, desimaniac, kowalski, JigSawFr             #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

heimdall_name: heimdall

################################
# Paths
################################

heimdall_role_paths_folder: "{{ heimdall_name }}"
heimdall_role_paths_location: "{{ server_appdata_path }}/{{ heimdall_role_paths_folder }}"
heimdall_role_paths_folders_list:
  - "{{ heimdall_role_paths_location }}"

################################
# Web
################################

heimdall_role_web_subdomain: "{{ heimdall_name }}"
heimdall_role_web_domain: "{{ user.domain }}"
heimdall_role_web_port: "80"
heimdall_role_web_url: "{{ 'https://' + (heimdall_role_web_subdomain + '.' + heimdall_role_web_domain
                   if (heimdall_role_web_subdomain | length > 0)
                   else heimdall_role_web_domain) }}"

################################
# DNS
################################

heimdall_role_dns_record: "{{ heimdall_role_web_subdomain }}"
heimdall_role_dns_zone: "{{ heimdall_role_web_domain }}"
heimdall_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

heimdall_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
heimdall_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
heimdall_role_traefik_middleware_custom: ""
heimdall_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
heimdall_role_traefik_enabled: true
heimdall_role_traefik_api_enabled: false
heimdall_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
heimdall_role_docker_container: "{{ heimdall_name }}"

# Image
heimdall_role_docker_image_pull: true
heimdall_role_docker_image_tag: "latest"
heimdall_role_docker_image: "lscr.io/linuxserver/heimdall:{{ heimdall_role_docker_image_tag }}"

# Envs
heimdall_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
heimdall_role_docker_envs_custom: {}
heimdall_role_docker_envs: "{{ heimdall_role_docker_envs_default
                          | combine(heimdall_role_docker_envs_custom) }}"

# Volumes
heimdall_role_docker_volumes_default:
  - "{{ heimdall_role_paths_location }}:/config"
heimdall_role_docker_volumes_custom: []
heimdall_role_docker_volumes: "{{ heimdall_role_docker_volumes_default
                             + heimdall_role_docker_volumes_custom }}"

# Hostname
heimdall_role_docker_hostname: "{{ heimdall_name }}"

# Networks
heimdall_role_docker_networks_alias: "{{ heimdall_name }}"
heimdall_role_docker_networks_default: []
heimdall_role_docker_networks_custom: []
heimdall_role_docker_networks: "{{ docker_networks_common
                              + heimdall_role_docker_networks_default
                              + heimdall_role_docker_networks_custom }}"

# Restart Policy
heimdall_role_docker_restart_policy: unless-stopped

# State
heimdall_role_docker_state: started
