##########################################################################
# Title:            Sandbox: Membarr                                     #
# Author(s):        CHAIR/Raneydazed                                     #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Set Default Plex instance
  ansible.builtin.set_fact:
    plex_name: "{{ plex_instances[0] }}"
  when: not plex_name is defined

# Plex Tasks
- name: "Settings | Check if '{{ lookup('role_var', '_paths_config_location', role='plex') | basename }}' exists"
  ansible.builtin.stat:
    path: "{{ lookup('role_var', '_paths_config_location', role='plex') }}"
  register: preferences_xml

- name: Settings | {{ plex_name }} info tasks
  when: preferences_xml.stat.exists
  block:
    - name: Settings | Fetch {{ plex_name }} info
      community.general.xml:
        path: "{{ lookup('role_var', '_paths_config_location', role='plex') }}"
        xpath: /Preferences
        content: attribute
      register: preferences_xml_resp
      ignore_errors: true

    - name: Settings | Register {{ plex_name }} Auth Token Value
      ansible.builtin.set_fact:
        plex_auth_token: "{{ preferences_xml_resp.matches[0].Preferences.PlexOnlineToken }}"

    - name: Settings | Register {{ plex_name }} Friendly Server Name
      ansible.builtin.set_fact:
        plex_friendly_name: "{{ preferences_xml_resp.matches[0].Preferences.FriendlyName }}"

    - name: Settings | Register {{ plex_name }} User Name
      ansible.builtin.set_fact:
        plex_online_username: "{{ preferences_xml_resp.matches[0].Preferences.PlexOnlineUsername }}"

- name: Settings | Check if `{{ lookup('role_var', '_paths_config_location', role='membarr') | basename }}` exists
  ansible.builtin.stat:
    path: "{{ lookup('role_var', '_paths_config_location', role='membarr') }}"
  register: membarr_config

- name: Settings | New `{{ lookup('role_var', '_paths_config_location', role='membarr') | basename }}` tasks
  when: not membarr_config.stat.exists
  block:
    - name: Settings | Import default `{{ lookup('role_var', '_paths_config_location', role='membarr') | basename }}`
      ansible.builtin.template:
        src: config.ini.j2
        dest: "{{ lookup('role_var', '_paths_config_location', role='membarr') }}"
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: "0664"
