##########################################################################
# Title:         Sandbox: Funkwhale | Default Variables                  #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

funkwhale_name: funkwhale

################################
# Paths
################################

funkwhale_role_paths_folder: "{{ funkwhale_name }}"
funkwhale_role_paths_location: "{{ server_appdata_path }}/{{ funkwhale_role_paths_folder }}"
funkwhale_role_paths_folders_list:
  - "{{ funkwhale_role_paths_location }}"
  - "{{ funkwhale_role_paths_location }}/data"

################################
# Web
################################

funkwhale_role_web_subdomain: "{{ funkwhale_name }}"
funkwhale_role_web_domain: "{{ user.domain }}"
funkwhale_role_web_port: "80"
funkwhale_role_web_url: "{{ 'https://' + (funkwhale_role_web_subdomain + '.' + funkwhale_role_web_domain
                    if (funkwhale_role_web_subdomain | length > 0)
                    else funkwhale_role_web_domain) }}"

################################
# DNS
################################

funkwhale_role_dns_record: "{{ funkwhale_role_web_subdomain }}"
funkwhale_role_dns_zone: "{{ funkwhale_role_web_domain }}"
funkwhale_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

funkwhale_role_traefik_sso_middleware: ""
funkwhale_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
funkwhale_role_traefik_middleware_custom: ""
funkwhale_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
funkwhale_role_traefik_enabled: true
funkwhale_role_traefik_api_enabled: false
funkwhale_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
funkwhale_role_docker_container: "{{ funkwhale_name }}"

# Image
funkwhale_role_docker_image_pull: true
funkwhale_role_docker_image_tag: "latest"
funkwhale_role_docker_image: "funkwhale/all-in-one:{{ funkwhale_role_docker_image_tag }}"

# Envs
funkwhale_role_docker_envs_default:
  FUNKWHALE_HOSTNAME: "{{ funkwhale_role_web_subdomain + '.' + funkwhale_role_web_domain }}"
  NESTED_PROXY: "1"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
funkwhale_role_docker_envs_custom: {}
funkwhale_role_docker_envs: "{{ funkwhale_role_docker_envs_default
                           | combine(funkwhale_role_docker_envs_custom) }}"

# Volumes
funkwhale_role_docker_volumes_default:
  - "{{ funkwhale_role_paths_location }}/data:/data"
  - "/mnt/unionfs:/music:ro"
funkwhale_role_docker_volumes_custom: []
funkwhale_role_docker_volumes: "{{ funkwhale_role_docker_volumes_default
                              + funkwhale_role_docker_volumes_custom }}"

# Hostname
funkwhale_role_docker_hostname: "{{ funkwhale_name }}"

# Networks
funkwhale_role_docker_networks_alias: "{{ funkwhale_name }}"
funkwhale_role_docker_networks_default: []
funkwhale_role_docker_networks_custom: []
funkwhale_role_docker_networks: "{{ docker_networks_common
                               + funkwhale_role_docker_networks_default
                               + funkwhale_role_docker_networks_custom }}"

# Restart Policy
funkwhale_role_docker_restart_policy: unless-stopped

# State
funkwhale_role_docker_state: started
