##########################################################################
# Title:            Sandbox: Apache TIKA | Default Variables             #
# Author(s):        JigSawFr                                             #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

tika_name: tika

################################
# Docker
################################

# Container
tika_docker_container: "{{ tika_name }}"

# Image
tika_docker_image_pull: true
tika_docker_image_tag: "latest"
tika_docker_image: "ghcr.io/paperless-ngx/tika:{{ tika_docker_image_tag }}"

# Envs
tika_docker_envs_default:
  TZ: "{{ tz }}"
tika_docker_envs_custom: {}
tika_docker_envs: "{{ tika_docker_envs_default
                      | combine(tika_docker_envs_custom) }}"

# Hostname
tika_docker_hostname: "{{ tika_name }}"

# Networks
tika_docker_networks_alias: "{{ tika_name }}"
tika_docker_networks_default: []
tika_docker_networks_custom: []
tika_docker_networks: "{{ docker_networks_common
                          + tika_docker_networks_default
                          + tika_docker_networks_custom }}"

# Restart Policy
tika_docker_restart_policy: always

# State
tika_docker_state: started
