##########################################################################
# Title:            Sandbox: Forgejo                                     #
# Author(s):        Thomvh, kowalski                                     #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

forgejo_name: forgejo

################################
# Paths
################################

forgejo_role_paths_folder: "{{ forgejo_name }}"
forgejo_role_paths_location: "{{ server_appdata_path }}/{{ forgejo_role_paths_folder }}"
forgejo_role_paths_folders_list:
  - "{{ forgejo_role_paths_location }}"

################################
# Web
################################

forgejo_role_web_subdomain: "{{ forgejo_name }}"
forgejo_role_web_domain: "{{ user.domain }}"
forgejo_role_web_port: "3000"
forgejo_role_web_url: "{{ 'https://' + (forgejo_role_web_subdomain + '.' + forgejo_role_web_domain
                  if (forgejo_role_web_subdomain | length > 0)
                  else forgejo_role_web_domain) }}"

################################
# DNS
################################

forgejo_role_dns_record: "{{ forgejo_role_web_subdomain }}"
forgejo_role_dns_zone: "{{ forgejo_role_web_domain }}"
forgejo_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

forgejo_role_traefik_sso_middleware: ""
forgejo_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
forgejo_role_traefik_middleware_custom: ""
forgejo_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
forgejo_role_traefik_enabled: true
forgejo_role_traefik_api_enabled: false
forgejo_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
forgejo_role_docker_container: "{{ forgejo_name }}"

# Image
forgejo_role_docker_image_pull: true
forgejo_role_docker_image_tag: "1.20" # the Codeberg container registry does not provide a "latest" tag
forgejo_role_docker_image: "codeberg.org/forgejo/forgejo:{{ forgejo_role_docker_image_tag }}"

# Envs
forgejo_role_docker_envs_default:
  USER_UID: "{{ uid }}"
  USER_GID: "{{ gid }}"
  DB_TYPE: "mysql"
  DB_HOST: "mariadb:3306"
  DB_USER: "root"
  DB_PASS: "password321"
  DB_DATABASE: "forgejo"
  DISABLE_SSH: "true"
  RUN_MODE: "prod"
  ROOT_URL: "{{ forgejo_role_web_url }}/"
forgejo_role_docker_envs_custom: {}
forgejo_role_docker_envs: "{{ forgejo_role_docker_envs_default | combine(forgejo_role_docker_envs_custom) }}"

# Volumes
forgejo_role_docker_volumes_default:
  - "{{ forgejo_role_paths_location }}:/data"
  - /etc/timezone:/etc/timezone:ro
  - /etc/localtime:/etc/localtime:ro
forgejo_role_docker_volumes_custom: []
forgejo_role_docker_volumes: "{{ forgejo_role_docker_volumes_default + forgejo_role_docker_volumes_custom }}"

# Hostname
forgejo_role_docker_hostname: "{{ forgejo_name }}"

# Networks
forgejo_role_docker_networks_alias: "{{ forgejo_name }}"
forgejo_role_docker_networks_default: []
forgejo_role_docker_networks_custom: []
forgejo_role_docker_networks: "{{ docker_networks_common + forgejo_role_docker_networks_default + forgejo_role_docker_networks_custom }}"

# Restart Policy
forgejo_role_docker_restart_policy: unless-stopped

# State
forgejo_role_docker_state: started

# Dependencies
forgejo_depends_on: "mariadb"
forgejo_depends_on_delay: "0"
forgejo_depends_on_healthchecks: "false"
