##########################################################################
# Title:            Sandbox: Nabarr   | Default Variables                #
# Author(s):        kowalski                                             #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

nabarr_name: nabarr

################################
# Paths
################################

nabarr_role_paths_folder: "{{ nabarr_name }}"
nabarr_role_paths_location: "{{ server_appdata_path }}/{{ nabarr_role_paths_folder }}"
nabarr_role_paths_folders_list:
  - "{{ nabarr_role_paths_location }}"
nabarr_role_paths_config_location: "{{ nabarr_role_paths_location }}/config.yml"

################################
# Docker
################################

# Container
nabarr_role_docker_container: "{{ nabarr_name }}"

# Image
nabarr_role_docker_image_pull: true
nabarr_role_docker_image_tag: "latest"
nabarr_role_docker_image_repo: "saltydk/nabarr"
nabarr_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='nabarr') }}:{{ lookup('role_var', '_docker_image_tag', role='nabarr') }}"

# Envs
nabarr_role_docker_envs_default:
  TZ: "{{ tz }}"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  APP_VERBOSITY: "0"
nabarr_role_docker_envs_custom: {}
nabarr_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='nabarr')
                             | combine(lookup('role_var', '_docker_envs_custom', role='nabarr')) }}"

# Volumes
nabarr_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='nabarr') }}:/config"
nabarr_role_docker_volumes_custom: []
nabarr_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='nabarr')
                                + lookup('role_var', '_docker_volumes_custom', role='nabarr') }}"

# Hostname
nabarr_role_docker_hostname: "{{ nabarr_name }}"

# Networks
nabarr_role_docker_networks_alias: "{{ nabarr_name }}"
nabarr_role_docker_networks_default: []
nabarr_role_docker_networks_custom: []
nabarr_role_docker_networks: "{{ docker_networks_common
                                 + lookup('role_var', '_docker_networks_default', role='nabarr')
                                 + lookup('role_var', '_docker_networks_custom', role='nabarr') }}"

# Restart Policy
nabarr_role_docker_restart_policy: unless-stopped

# State
nabarr_role_docker_state: started
