#########################################################################
# Title:            Sandbox: Maybe Finance                              #
# Author(s):        cartermcalister                                     #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

maybe_finance_name: maybe-finance

################################
# Settings
################################

maybe_finance_postgres_name: "{{ maybe_finance_name }}-postgres"
maybe_finance_postgres_role_docker_env_db: "{{ maybe_finance_name }}"
maybe_finance_postgres_role_docker_image_tag: "16"
maybe_finance_postgres_role_docker_image_repo: "postgres"
maybe_finance_postgres_role_paths_folder: "{{ maybe_finance_name }}"
maybe_finance_postgres_role_paths_location: "{{ server_appdata_path }}/{{ maybe_finance_postgres_role_paths_folder }}/postgres"

################################
# Paths
################################

maybe_finance_role_paths_folder: "{{ maybe_finance_name }}"
maybe_finance_role_paths_location: "{{ server_appdata_path }}/{{ maybe_finance_role_paths_folder }}"
maybe_finance_role_paths_folders_list:
  - "{{ maybe_finance_role_paths_location }}"

################################
# Web
################################

maybe_finance_role_web_subdomain: "{{ maybe_finance_name }}"
maybe_finance_role_web_domain: "{{ user.domain }}"
maybe_finance_role_web_port: "3000"
maybe_finance_role_web_url: "{{ 'https://' + (maybe_finance_role_web_subdomain + '.' + maybe_finance_role_web_domain
                         if (maybe_finance_role_web_subdomain | length > 0)
                         else maybe_finance_role_web_domain) }}"

################################
# DNS
################################

maybe_finance_role_dns_record: "{{ maybe_finance_role_web_subdomain }}"
maybe_finance_role_dns_zone: "{{ maybe_finance_role_web_domain }}"
maybe_finance_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

maybe_finance_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
maybe_finance_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
maybe_finance_role_traefik_middleware_custom: ""
maybe_finance_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
maybe_finance_role_traefik_enabled: true
maybe_finance_role_traefik_api_enabled: false
maybe_finance_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
maybe_finance_role_docker_container: "{{ maybe_finance_name }}"

# Image
maybe_finance_role_docker_image_pull: true
maybe_finance_role_docker_image_tag: "latest"
maybe_finance_role_docker_image: "ghcr.io/maybe-finance/maybe:{{ maybe_finance_role_docker_image_tag }}"

# Envs
maybe_finance_role_docker_envs_default:
  TZ: "{{ tz }}"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  SELF_HOSTED: "true"
  RAILS_FORCE_SSL: "false"
  RAILS_ASSUME_SSL: "false"
  GOOD_JOB_EXECUTION_MODE: "async"
  SECRET_KEY_BASE: "{{ maybe_finance_saltbox_facts.facts.secret_key_base }}"
  DB_USERNAME: "{{ postgres_role_docker_env_user }}"
  DB_PASSWORD: "{{ postgres_role_docker_env_password }}"
  DB_HOST: "{{ maybe_finance_postgres_name }}"
  DB_PORT: "5432"
  REDIS_URL: "redis://{{ maybe_finance_name }}-redis:6379/1"
  POSTGRES_USER: "{{ postgres_role_docker_env_user }}"
  POSTGRES_PASSWORD: "{{ postgres_role_docker_env_password }}"
maybe_finance_role_docker_envs_custom: {}
maybe_finance_role_docker_envs: "{{ maybe_finance_role_docker_envs_default
                           | combine(maybe_finance_role_docker_envs_custom) }}"

# Volumes
maybe_finance_role_docker_volumes_default:
  - "{{ maybe_finance_role_paths_location }}:/rails/storage"
maybe_finance_role_docker_volumes_custom: []
maybe_finance_role_docker_volumes: "{{ maybe_finance_role_docker_volumes_default
                              + maybe_finance_role_docker_volumes_custom }}"

# Hostname
maybe_finance_role_docker_hostname: "{{ maybe_finance_name }}"

# Networks
maybe_finance_role_docker_networks_alias: "{{ maybe_finance_name }}"
maybe_finance_role_docker_networks_default: []
maybe_finance_role_docker_networks_custom: []
maybe_finance_role_docker_networks: "{{ docker_networks_common
                               + maybe_finance_role_docker_networks_default
                               + maybe_finance_role_docker_networks_custom }}"

# Restart Policy
maybe_finance_role_docker_restart_policy: unless-stopped

# State
maybe_finance_role_docker_state: started

# Dependencies
maybe_finance_depends_on: "{{ maybe_finance_postgres_name }}"
maybe_finance_depends_on_delay: "5"
maybe_finance_depends_on_healthchecks: "true"
