##########################################################################
# Title:         Sandbox: PufferPanel | Default Variables                #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

pufferpanel_name: pufferpanel

################################
# Paths
################################

pufferpanel_role_paths_folder: "{{ pufferpanel_name }}"
pufferpanel_role_paths_location: "{{ server_appdata_path }}/{{ pufferpanel_role_paths_folder }}"
pufferpanel_role_paths_folders_list:
  - "{{ pufferpanel_role_paths_location }}/config"
  - "{{ pufferpanel_role_paths_location }}/servers"

################################
# Web
################################

pufferpanel_role_web_subdomain: "{{ pufferpanel_name }}"
pufferpanel_role_web_domain: "{{ user.domain }}"
pufferpanel_role_web_port: "8080"
pufferpanel_role_web_url: "{{ 'https://' + (pufferpanel_role_web_subdomain + '.' + pufferpanel_role_web_domain
                           if (pufferpanel_role_web_subdomain | length > 0)
                           else pufferpanel_role_web_domain) }}"

################################
# DNS
################################

pufferpanel_role_dns_record: "{{ pufferpanel_role_web_subdomain }}"
pufferpanel_role_dns_zone: "{{ pufferpanel_role_web_domain }}"
pufferpanel_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

pufferpanel_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
pufferpanel_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
pufferpanel_role_traefik_middleware_custom: ""
pufferpanel_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
pufferpanel_role_traefik_enabled: true

################################
# Docker
################################

# Container
pufferpanel_role_docker_container: "{{ pufferpanel_name }}"

# Image
pufferpanel_role_docker_image_pull: true
pufferpanel_role_docker_image_tag: "latest"
pufferpanel_role_docker_image: "pufferpanel/pufferpanel:{{ pufferpanel_role_docker_image_tag }}"

# Ports
pufferpanel_role_docker_ports_defaults:
  - "5657:5657"
pufferpanel_role_docker_ports_custom: []
pufferpanel_role_docker_ports: "{{ pufferpanel_role_docker_ports_defaults
                              + pufferpanel_role_docker_ports_custom }}"

# Envs
pufferpanel_role_docker_envs_default:
  TZ: "{{ tz }}"
  PUFFER_DAEMON_DATA_SERVERS: "{{ pufferpanel_role_paths_location }}/servers"
pufferpanel_role_docker_envs_custom: {}
pufferpanel_role_docker_envs: "{{ pufferpanel_role_docker_envs_default
                             | combine(pufferpanel_role_docker_envs_custom) }}"

# Volumes
pufferpanel_role_docker_volumes_default:
  - "{{ pufferpanel_role_paths_location }}/config:/etc/pufferpanel"
  - "{{ pufferpanel_role_paths_location }}/servers:{{ pufferpanel_role_paths_location }}/servers"
  - "/var/run/docker.sock:/var/run/docker.sock"
pufferpanel_role_docker_volumes_custom: []
pufferpanel_role_docker_volumes: "{{ pufferpanel_role_docker_volumes_default
                                + pufferpanel_role_docker_volumes_custom }}"

# Hostname
pufferpanel_role_docker_hostname: "{{ pufferpanel_name }}"

# Networks
pufferpanel_role_docker_networks_alias: "{{ pufferpanel_name }}"
pufferpanel_role_docker_networks_default: []
pufferpanel_role_docker_networks_custom: []
pufferpanel_role_docker_networks: "{{ docker_networks_common
                                 + pufferpanel_role_docker_networks_default
                                 + pufferpanel_role_docker_networks_custom }}"

# Restart Policy
pufferpanel_role_docker_restart_policy: unless-stopped

# State
pufferpanel_role_docker_state: started
