##########################################################################
# Title:            Sandbox: JDownloader2 | Default Variables            #
# Author(s):        kowalski, desimaniac                                 #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

jdownloader2_name: jdownloader2

################################
# Paths
################################

jdownloader2_role_paths_folder: "{{ jdownloader2_name }}"
jdownloader2_role_paths_location: "{{ server_appdata_path }}/{{ jdownloader2_role_paths_folder }}"
jdownloader2_role_paths_downloads_location: "/mnt/local/downloads/{{ jdownloader2_name }}/output"
jdownloader2_role_paths_tools_location: "{{ jdownloader2_role_paths_location }}/config/libs"
jdownloader2_role_paths_folders_list:
  - "{{ jdownloader2_role_paths_location }}"
  - "{{ jdownloader2_role_paths_location }}/config"
  - "{{ jdownloader2_role_paths_tools_location }}"
  - "{{ jdownloader2_role_paths_downloads_location }}"

################################
# Web
################################

jdownloader2_role_web_subdomain: "{{ jdownloader2_name }}"
jdownloader2_role_web_domain: "{{ user.domain }}"
jdownloader2_role_web_port: "5800"
jdownloader2_role_web_url: "{{ 'https://' + (jdownloader2_role_web_subdomain + '.' + jdownloader2_role_web_domain
                       if (jdownloader2_role_web_subdomain | length > 0)
                       else jdownloader2_role_web_domain) }}"

################################
# DNS
################################

jdownloader2_role_dns_record: "{{ jdownloader2_role_web_subdomain }}"
jdownloader2_role_dns_zone: "{{ jdownloader2_role_web_domain }}"
jdownloader2_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

jdownloader2_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
jdownloader2_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
jdownloader2_role_traefik_middleware_custom: ""
jdownloader2_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
jdownloader2_role_traefik_enabled: true
jdownloader2_role_traefik_api_enabled: false
jdownloader2_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
jdownloader2_role_docker_container: "{{ jdownloader2_name }}"

# Image
jdownloader2_role_docker_image_pull: true
jdownloader2_role_docker_image_tag: "latest"
jdownloader2_role_docker_image: "jlesage/jdownloader-2:{{ jdownloader2_role_docker_image_tag }}"

# Envs
jdownloader2_role_docker_envs_default:
  USER_ID: "{{ uid }}"
  GROUP_ID: "{{ gid }}"
  TZ: "{{ tz }}"
  DISPLAY_WIDTH: "1280"
  DISPLAY_HEIGHT: "768"
  VNC_PASSWORD: "{{ user.pass }}"
  CLEAN_TMP_DIR: "1"
  UMASK: "000"
  ENABLE_CJK_FONT: "1"
jdownloader2_role_docker_envs_custom: {}
jdownloader2_role_docker_envs: "{{ jdownloader2_role_docker_envs_default
                              | combine(jdownloader2_role_docker_envs_custom) }}"

# Volumes
jdownloader2_role_docker_volumes_default:
  - "{{ jdownloader2_role_paths_location }}/config:/config"
  - "{{ jdownloader2_role_paths_downloads_location }}:/output"
jdownloader2_role_docker_volumes_custom: []
jdownloader2_role_docker_volumes: "{{ jdownloader2_role_docker_volumes_default
                                 + jdownloader2_role_docker_volumes_custom }}"

# Hostname
jdownloader2_role_docker_hostname: "{{ jdownloader2_name }}"

# Networks
jdownloader2_role_docker_networks_alias: "{{ jdownloader2_name }}"
jdownloader2_role_docker_networks_default: []
jdownloader2_role_docker_networks_custom: []
jdownloader2_role_docker_networks: "{{ docker_networks_common
                                  + jdownloader2_role_docker_networks_default
                                  + jdownloader2_role_docker_networks_custom }}"

# Restart Policy
jdownloader2_role_docker_restart_policy: unless-stopped

# State
jdownloader2_role_docker_state: started
