##########################################################################
# Title:         Sandbox: Booksonic | Default Variables                  #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

booksonic_name: booksonic

################################
# Paths
################################

booksonic_paths_folder: "{{ booksonic_name }}"
booksonic_paths_location: "{{ server_appdata_path }}/{{ booksonic_paths_folder }}"
booksonic_paths_folders_list:
  - "{{ booksonic_paths_location }}"

################################
# Web
################################

booksonic_web_subdomain: "{{ booksonic_name }}"
booksonic_web_domain: "{{ user.domain }}"
booksonic_web_port: "4040"
booksonic_web_url: "{{ 'https://' + (booksonic_web_subdomain + '.' + booksonic_web_domain
                    if (booksonic_web_subdomain | length > 0)
                    else booksonic_web_domain) }}"

################################
# DNS
################################

booksonic_dns_record: "{{ booksonic_web_subdomain }}"
booksonic_dns_zone: "{{ booksonic_web_domain }}"
booksonic_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

booksonic_traefik_sso_middleware: ""
booksonic_traefik_middleware_default: "{{ traefik_default_middleware }}"
booksonic_traefik_middleware_custom: ""
booksonic_traefik_certresolver: "{{ traefik_default_certresolver }}"
booksonic_traefik_enabled: true

################################
# Docker
################################

# Container
booksonic_docker_container: "{{ booksonic_name }}"

# Image
booksonic_docker_image_pull: true
booksonic_docker_image_tag: "2201.1.0"
booksonic_docker_image: "lscr.io/linuxserver/booksonic-air:{{ booksonic_docker_image_tag }}"

# Ports
booksonic_docker_ports_defaults: []
booksonic_docker_ports_custom: []
booksonic_docker_ports: "{{ booksonic_docker_ports_defaults
                            + booksonic_docker_ports_custom }}"

# Envs
booksonic_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  JAVA_OPTS: "-Dserver.use-forward-headers=true"
booksonic_docker_envs_custom: {}
booksonic_docker_envs: "{{ booksonic_docker_envs_default
                           | combine(booksonic_docker_envs_custom) }}"

# Volumes
booksonic_docker_volumes_default:
  - "{{ booksonic_paths_location }}:/config"
  - "/mnt/unionfs/Media/Audiobooks:/audiobooks"
  - "/mnt/unionfs/Media/Podcasts:/podcasts"
  - "/mnt/unionfs/Media:/othermedia"
booksonic_docker_volumes_custom: []
booksonic_docker_volumes: "{{ booksonic_docker_volumes_default
                              + booksonic_docker_volumes_custom }}"

# Hostname
booksonic_docker_hostname: "{{ booksonic_name }}"

# Networks
booksonic_docker_networks_alias: "{{ booksonic_name }}"
booksonic_docker_networks_default: []
booksonic_docker_networks_custom: []
booksonic_docker_networks: "{{ docker_networks_common
                               + booksonic_docker_networks_default
                               + booksonic_docker_networks_custom }}"

# Restart Policy
booksonic_docker_restart_policy: unless-stopped

# State
booksonic_docker_state: started
