##########################################################################
# Title:            Sandbox: Miniflux | Default Variables                #
# Author(s):        powerdude                                            #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

miniflux_name: miniflux

################################
# Settings
################################

miniflux_admin_username: "{{ user.name }}"
miniflux_admin_password: "{{ user.pass }}"
miniflux_create_admin: "1"
miniflux_run_migrations: "1"
miniflux_postgres_username: "{{ lookup('vars', miniflux_name + '_postgres_role_docker_env_user', default=postgres_role_docker_env_user) }}"
miniflux_postgres_password: "{{ lookup('vars', miniflux_name + '_postgres_role_docker_env_password', default=postgres_role_docker_env_password) }}"

miniflux_postgres_name: "{{ miniflux_name }}-postgres"
miniflux_postgres_role_docker_env_db: "miniflux"
miniflux_postgres_role_docker_image_tag: "14-alpine"
miniflux_postgres_role_docker_image_repo: "postgres"
miniflux_postgres_role_paths_folder: "{{ miniflux_name }}"
miniflux_postgres_role_paths_location: "{{ server_appdata_path }}/{{ postgres_role_paths_folder }}/postgres"

################################
# Paths
################################

miniflux_role_paths_folder: "{{ miniflux_name }}"
miniflux_role_paths_location: "{{ server_appdata_path }}/{{ miniflux_role_paths_folder }}"
miniflux_role_paths_folders_list:
  - "{{ miniflux_role_paths_location }}"

################################
# Web
################################

miniflux_role_web_subdomain: "{{ miniflux_name }}"
miniflux_role_web_domain: "{{ user.domain }}"
miniflux_role_web_port: "8080"
miniflux_role_web_url: "{{ 'https://' + (miniflux_role_web_subdomain + '.' + miniflux_role_web_domain
                   if (miniflux_role_web_subdomain | length > 0)
                   else miniflux_role_web_domain) }}"

################################
# DNS
################################

miniflux_role_dns_record: "{{ miniflux_role_web_subdomain }}"
miniflux_role_dns_zone: "{{ miniflux_role_web_domain }}"
miniflux_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

miniflux_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
miniflux_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
miniflux_role_traefik_middleware_custom: ""
miniflux_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
miniflux_role_traefik_enabled: true
miniflux_role_traefik_api_enabled: false
miniflux_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
miniflux_role_docker_container: "{{ miniflux_name }}"

# Image
miniflux_role_docker_image_pull: true
miniflux_role_docker_image_tag: "latest"
miniflux_role_docker_image: "miniflux/miniflux:{{ miniflux_role_docker_image_tag }}"

# Envs
miniflux_role_docker_envs_default:
  DATABASE_URL: "postgres://{{ miniflux_postgres_username }}:{{ miniflux_postgres_password }}@{{ miniflux_postgres_name }}/{{ miniflux_postgres_role_docker_env_db }}?sslmode=disable"
  RUN_MIGRATIONS: "{{ miniflux_run_migrations }}"
  CREATE_ADMIN: "{{ miniflux_create_admin }}"
  ADMIN_USERNAME: "{{ miniflux_admin_username }}"
  ADMIN_PASSWORD: "{{ miniflux_admin_password }}"
miniflux_role_docker_envs_custom: {}
miniflux_role_docker_envs: "{{ miniflux_role_docker_envs_default
                          | combine(miniflux_role_docker_envs_custom) }}"

# Volumes
miniflux_role_docker_volumes_default:
  - /etc/localtime:/etc/localtime:ro
miniflux_role_docker_volumes_custom: []
miniflux_role_docker_volumes: "{{ miniflux_role_docker_volumes_default
                             + miniflux_role_docker_volumes_custom }}"

# Hostname
miniflux_role_docker_hostname: "{{ miniflux_name }}"

# Networks
miniflux_role_docker_networks_alias: "{{ miniflux_name }}"
miniflux_role_docker_networks_default: []
miniflux_role_docker_networks_custom: []
miniflux_role_docker_networks: "{{ docker_networks_common
                              + miniflux_role_docker_networks_default
                              + miniflux_role_docker_networks_custom }}"

# Restart Policy
miniflux_role_docker_restart_policy: unless-stopped

# State
miniflux_role_docker_state: started

# Dependencies
minuflux_depends_on: "{{ minuflux_postgres_name }}"
minuflux_depends_on_delay: "0"
minuflux_depends_on_healthchecks: "false"
