#########################################################################
# Title:         Sandbox: Plex-Auto-Languages                           #
# Author(s):     hackmonker                                             #
# URL:           https://github.com/saltyorg/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

plex_auto_languages_name: plex-auto-languages

################################
# Paths
################################

plex_auto_languages_role_paths_folder: "{{ plex_auto_languages_name }}"
plex_auto_languages_role_paths_location: "{{ server_appdata_path }}/{{ plex_auto_languages_role_paths_folder }}"
plex_auto_languages_role_paths_config_location: "{{ plex_auto_languages_role_paths_location }}/config.yaml"
plex_auto_languages_role_paths_folders_list:
  - "{{ plex_auto_languages_role_paths_location }}"

################################
# Docker
################################

# Container
plex_auto_languages_role_docker_container: "{{ plex_auto_languages_name }}"

# Image
plex_auto_languages_role_docker_image_tag: "latest"
plex_auto_languages_role_docker_image_repo: "journeyover/plex-auto-languages"
plex_auto_languages_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='plex_auto_languages') }}:{{ lookup('role_var', '_docker_image_tag', role='plex_auto_languages') }}"
plex_auto_languages_role_docker_image_pull: true

# Envs
plex_auto_languages_role_docker_envs_default:
  TZ: "{{ tz }}"
plex_auto_languages_role_docker_envs_custom: {}
plex_auto_languages_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='plex_auto_languages')
                                          | combine(lookup('role_var', '_docker_envs_custom', role='plex_auto_languages')) }}"

# Volumes
plex_auto_languages_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='plex_auto_languages') }}:/config"
plex_auto_languages_role_docker_volumes_custom: []
plex_auto_languages_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='plex_auto_languages')
                                             + lookup('role_var', '_docker_volumes_custom', role='plex_auto_languages') }}"

# Hostname
plex_auto_languages_role_docker_hostname: "{{ plex_auto_languages_name }}"

# Networks
plex_auto_languages_role_docker_networks_alias: "{{ plex_auto_languages_name }}"
plex_auto_languages_role_docker_networks_default: []
plex_auto_languages_role_docker_networks_custom: []
plex_auto_languages_role_docker_networks: "{{ docker_networks_common
                                              + lookup('role_var', '_docker_networks_default', role='plex_auto_languages')
                                              + lookup('role_var', '_docker_networks_custom', role='plex_auto_languages') }}"

# Restart Policy
plex_auto_languages_role_docker_restart_policy: unless-stopped

# State
plex_auto_languages_role_docker_state: started

# Stop Timeout
plex_auto_languages_role_docker_stop_timeout: 10

# User
plex_auto_languages_role_docker_user: "{{ uid }}:{{ gid }}"
