#########################################################################
# Title:            Sandbox: Stash Auth Task                            #
# Author(s):        owine                                               #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Auth | Check if 'config.yml' exists
  ansible.builtin.stat:
    path: "{{ stash_role_paths_location }}/config/config.yml"
  register: stash_config

- name: Auth | Print Message
  ansible.builtin.debug:
    msg:
      - "Please go to {{ stash_role_web_url }} and complete the initial setup."
      - "You have 10 minutes to finish."

- name: Auth | Wait for 'config.yml' to be created
  ansible.builtin.wait_for:
    path: "{{ stash_role_paths_location }}/config/config.yml"
    state: present
    timeout: 600

- name: Stop Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/stop_docker_container.yml"

- name: Allow public access without auth
  ansible.builtin.shell: |
    yyq -i '.dangerous_allow_public_without_auth = "true"' {{ stash_role_paths_location }}/config/config.yml
  become: true
  become_user: "{{ user.name }}"

- name: Remove tripwire
  ansible.builtin.shell: |
    yyq -i 'del(.security_tripwire_accessed_from_public_internet)' {{ stash_role_paths_location }}/config/config.yml
  become: true
  become_user: "{{ user.name }}"

- name: Restart Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/start_docker_container.yml"
