##########################################################################
# Title:            Sandbox: InfluxDB                                    #
# Author(s):        desimaniac, kowalski                                 #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

influxdb_name: influxdb

################################
# Paths
################################

influxdb_paths_folder: "{{ influxdb_name }}"
influxdb_paths_location: "{{ server_appdata_path }}/{{ influxdb_paths_folder }}"
influxdb_paths_folders_list:
  - "{{ influxdb_paths_location }}"

################################
# Docker
################################

# Container
influxdb_docker_container: "{{ influxdb_name }}"

# Image
influxdb_docker_image_pull: true
influxdb_docker_image_tag: "1.8.4"
influxdb_docker_image: "influxdb:{{ influxdb_docker_image_tag }}"

# Volumes
influxdb_docker_volumes_default:
  - "{{ influxdb_paths_location }}:/var/lib/influxdb"
influxdb_docker_volumes_custom: []
influxdb_docker_volumes: "{{ influxdb_docker_volumes_default
                             + influxdb_docker_volumes_custom }}"

# Hostname
influxdb_docker_hostname: "{{ influxdb_name }}"

# Networks
influxdb_docker_networks_alias: "{{ influxdb_name }}"
influxdb_docker_networks_default: []
influxdb_docker_networks_custom: []
influxdb_docker_networks: "{{ docker_networks_common
                              + influxdb_docker_networks_default
                              + influxdb_docker_networks_custom }}"

# Restart Policy
influxdb_docker_restart_policy: unless-stopped

# State
influxdb_docker_state: started
