#########################################################################
# Title:         Sandbox: AdGuard Home | Default Variables              #
# Author(s):     sevos                                                  #
# URL:           https://github.com/saltyorg/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

adguardhome_name: adguardhome

################################
# Paths
################################

adguardhome_role_paths_folder: "{{ adguardhome_name }}"
adguardhome_role_paths_location: "{{ server_appdata_path }}/{{ adguardhome_role_paths_folder }}"
adguardhome_role_paths_config_path: "{{ adguardhome_role_paths_location }}/conf/AdGuardHome.yaml"
adguardhome_role_paths_folders_list:
  - "{{ adguardhome_role_paths_location }}"
  - "{{ adguardhome_role_paths_location }}/conf"
  - "{{ adguardhome_role_paths_location }}/work"
  - "{{ adguardhome_role_paths_location }}/work/data"
  - "{{ adguardhome_role_paths_location }}/work/data/filters"

################################
# Web
################################

adguardhome_role_web_subdomain: "{{ adguardhome_name }}"
adguardhome_role_web_domain: "{{ user.domain }}"
adguardhome_role_web_port: "3000"
adguardhome_role_web_url: "{{ 'https://' + (adguardhome_role_web_subdomain + '.' + adguardhome_role_web_domain
                      if (adguardhome_role_web_subdomain | length > 0)
                      else adguardhome_role_web_domain) }}"

################################
# DNS
################################

adguardhome_role_dns_record: "{{ adguardhome_role_web_subdomain }}"
adguardhome_role_dns_zone: "{{ adguardhome_role_web_domain }}"
adguardhome_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

adguardhome_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
adguardhome_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
adguardhome_role_traefik_middleware_custom: ""
adguardhome_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
adguardhome_role_traefik_enabled: true
adguardhome_role_traefik_api_enabled: true
adguardhome_role_traefik_api_endpoint: "PathPrefix(`/dns-query`)"

################################
# Docker
################################

# Container
adguardhome_role_docker_container: "{{ adguardhome_name }}"

# Image
adguardhome_role_docker_image_pull: true
adguardhome_role_docker_image_tag: "latest"
adguardhome_role_docker_image: "adguard/adguardhome:{{ adguardhome_role_docker_image_tag }}"

# Envs
adguardhome_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
adguardhome_role_docker_envs_custom: {}
adguardhome_role_docker_envs: "{{ adguardhome_role_docker_envs_default
                             | combine(adguardhome_role_docker_envs_custom) }}"

# Volumes
adguardhome_role_docker_volumes_default:
  - "{{ adguardhome_role_paths_location }}/work:/opt/adguardhome/work"
  - "{{ adguardhome_role_paths_location }}/conf:/opt/adguardhome/conf"
adguardhome_role_docker_volumes_custom: []
adguardhome_role_docker_volumes: "{{ adguardhome_role_docker_volumes_default }}"

# Hostname
adguardhome_role_docker_hostname: "{{ adguardhome_name }}"

# Networks
adguardhome_role_docker_networks_alias: "{{ adguardhome_name }}"
adguardhome_role_docker_networks_default: []
adguardhome_role_docker_networks_custom: []
adguardhome_role_docker_networks: "{{ docker_networks_common
                                 + adguardhome_role_docker_networks_default
                                 + adguardhome_role_docker_networks_custom }}"

# Restart Policy
adguardhome_role_docker_restart_policy: unless-stopped

# State
adguardhome_role_docker_state: started
