#########################################################################
# Title:            Sandbox: Apprise                                    #
# Author(s):        owine, kowalski                                     #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

apprise_name: apprise

################################
# Paths
################################

apprise_role_paths_folder: "{{ apprise_name }}"
apprise_role_paths_location: "{{ server_appdata_path }}/{{ apprise_role_paths_folder }}"
apprise_role_paths_folders_list:
  - "{{ apprise_role_paths_location }}"

################################
# Web
################################

apprise_role_web_subdomain: "{{ apprise_name }}"
apprise_role_web_domain: "{{ user.domain }}"
apprise_role_web_port: "8000"
apprise_role_web_url: "{{ 'https://' + (apprise_role_web_subdomain + '.' + apprise_role_web_domain
                  if (apprise_role_web_subdomain | length > 0)
                  else apprise_role_web_domain) }}"

################################
# DNS
################################

apprise_role_dns_record: "{{ apprise_role_web_subdomain }}"
apprise_role_dns_zone: "{{ apprise_role_web_domain }}"
apprise_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

apprise_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
apprise_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
apprise_role_traefik_middleware_custom: ""
apprise_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
apprise_role_traefik_enabled: true

################################
# Docker
################################

# Container
apprise_role_docker_container: "{{ apprise_name }}"

# Image
apprise_role_docker_image_pull: true
apprise_role_docker_image_tag: "latest"
apprise_role_docker_image: "lscr.io/linuxserver/apprise-api:{{ apprise_role_docker_image_tag }}"

# Envs
apprise_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
apprise_role_docker_envs_custom: {}
apprise_role_docker_envs: "{{ apprise_role_docker_envs_default
                         | combine(apprise_role_docker_envs_custom) }}"

# Volumes
apprise_role_docker_volumes_default:
  - "{{ apprise_role_paths_location }}:/config"
apprise_role_docker_volumes_custom: []
apprise_role_docker_volumes: "{{ apprise_role_docker_volumes_default
                            + apprise_role_docker_volumes_custom }}"

# Hostname
apprise_role_docker_hostname: "{{ apprise_name }}"

# Networks
apprise_role_docker_networks_alias: "{{ apprise_name }}"
apprise_role_docker_networks_default: []
apprise_role_docker_networks_custom: []
apprise_role_docker_networks: "{{ docker_networks_common
                             + apprise_role_docker_networks_default
                             + apprise_role_docker_networks_custom }}"

# Restart Policy
apprise_role_docker_restart_policy: unless-stopped

# State
apprise_role_docker_state: started
