##########################################################################
# Title:            Sandbox: Tdarr   | Default Variables                 #
# Author(s):        kowalski                                             #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

tdarr_name: tdarr

################################
# Settings
################################

tdarr_server_port: "8266"
tdarr_server_external: false

################################
# Paths
################################

tdarr_role_paths_folder: "{{ tdarr_name }}"
tdarr_role_paths_location: "{{ server_appdata_path }}/{{ tdarr_role_paths_folder }}"
tdarr_role_paths_server_location: "{{ tdarr_role_paths_location }}/server"
tdarr_role_paths_configs_location: "{{ tdarr_role_paths_location }}/configs"
tdarr_role_paths_logs_location: "{{ tdarr_role_paths_location }}/logs"
tdarr_role_paths_transcodes_location: "{{ transcodes_path }}/{{ tdarr_role_paths_folder }}"
tdarr_role_paths_folders_list:
  - "{{ tdarr_role_paths_location }}"
  - "{{ tdarr_role_paths_server_location }}"
  - "{{ tdarr_role_paths_configs_location }}"
  - "{{ tdarr_role_paths_logs_location }}"
  - "{{ tdarr_role_paths_transcodes_location }}"

################################
# Web
################################

tdarr_role_web_subdomain: "{{ tdarr_name }}"
tdarr_role_web_domain: "{{ user.domain }}"
tdarr_role_web_port: "8265"
tdarr_role_web_url: "{{ 'https://' + (tdarr_role_web_subdomain + '.' + tdarr_role_web_domain
                     if (tdarr_role_web_subdomain | length > 0)
                     else tdarr_role_web_domain) }}"

################################
# DNS
################################

tdarr_role_dns_record: "{{ tdarr_role_web_subdomain }}"
tdarr_role_dns_zone: "{{ tdarr_role_web_domain }}"
tdarr_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

tdarr_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
tdarr_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
tdarr_role_traefik_middleware_custom: ""
tdarr_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
tdarr_role_traefik_enabled: true
tdarr_role_traefik_api_enabled: false
tdarr_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
tdarr_role_docker_container: "{{ tdarr_name }}"

# Image
tdarr_role_docker_image_pull: true
tdarr_role_docker_image_tag: "latest"
tdarr_role_docker_image: "haveagitgat/tdarr:{{ tdarr_role_docker_image_tag }}"

# Ports
tdarr_role_docker_ports_defaults:
  - "{{ tdarr_server_port }}:{{ tdarr_server_port }}"
tdarr_role_docker_ports_custom: []
tdarr_role_docker_ports: "{{ tdarr_role_docker_ports_defaults if (tdarr_server_external) else []
                             + tdarr_role_docker_ports_custom }}"

# Envs
tdarr_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  serverIP: "0.0.0.0"
  webUIPort: "8265"
  serverPort: "{{ tdarr_server_port }}"
  internalNode: "true"
  inContainer: "true"
tdarr_role_docker_envs_custom: {}
tdarr_role_docker_envs: "{{ tdarr_role_docker_envs_default
                            | combine(tdarr_role_docker_envs_custom) }}"

# Volumes
tdarr_role_docker_volumes_default:
  - "{{ tdarr_role_paths_configs_location }}:/app/configs"
  - "{{ tdarr_role_paths_server_location }}:/app/server"
  - "{{ tdarr_role_paths_logs_location }}:/app/logs"
  - "{{ tdarr_role_paths_transcodes_location }}:/temp"
  - "/mnt/unionfs/Media:/media"
  - "/mnt/unionfs/Media/Movies:/movies"
  - "/mnt/unionfs/Media/TV:/tv"
  - "/dev/shm:/dev/shm"
tdarr_role_docker_volumes_custom: []
tdarr_role_docker_volumes: "{{ tdarr_role_docker_volumes_default
                               + tdarr_role_docker_volumes_custom }}"

# Hostname
tdarr_role_docker_hostname: "{{ tdarr_name }}"

# Networks
tdarr_role_docker_networks_alias: "{{ tdarr_name }}"
tdarr_role_docker_networks_default: []
tdarr_role_docker_networks_custom: []
tdarr_role_docker_networks: "{{ docker_networks_common
                                + tdarr_role_docker_networks_default
                                + tdarr_role_docker_networks_custom }}"

# Restart Policy
tdarr_role_docker_restart_policy: unless-stopped

# State
tdarr_role_docker_state: started
