##########################################################################
# Title:         Sandbox: Joplin | Default Variables                     #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

joplin_name: joplin

################################
# Settings
################################

joplin_postgres_name: "{{ joplin_name }}-postgres"
joplin_postgres_role_docker_image_tag: "13"
joplin_postgres_role_docker_image_repo: "postgres"
joplin_postgres_role_docker_env_db: "joplin"
joplin_postgres_role_docker_env_user: "joplin"
joplin_postgres_role_docker_env_password: "joplin"
joplin_postgres_role_paths_folder: "{{ joplin_name }}"

################################
# Paths
################################

joplin_role_paths_folder: "{{ joplin_name }}"
joplin_role_paths_location: "{{ server_appdata_path }}/{{ joplin_role_paths_folder }}"
joplin_role_paths_folders_list:
  - "{{ joplin_role_paths_location }}"

################################
# Web
################################

joplin_role_web_subdomain: "{{ joplin_name }}"
joplin_role_web_domain: "{{ user.domain }}"
joplin_role_web_port: "22300"
joplin_role_web_url: "{{ 'https://' + (joplin_role_web_subdomain + '.' + joplin_role_web_domain
                 if (joplin_role_web_subdomain | length > 0)
                 else joplin_role_web_domain) }}"

################################
# DNS
################################

joplin_role_dns_record: "{{ joplin_role_web_subdomain }}"
joplin_role_dns_zone: "{{ joplin_role_web_domain }}"
joplin_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

joplin_role_traefik_sso_middleware: ""
joplin_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
joplin_role_traefik_middleware_custom: ""
joplin_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
joplin_role_traefik_enabled: true
joplin_role_traefik_api_enabled: false
joplin_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
joplin_role_docker_container: "{{ joplin_name }}"

# Image
joplin_role_docker_image_pull: true
joplin_role_docker_image_tag: "latest"
joplin_role_docker_image: "joplin/server:{{ joplin_role_docker_image_tag }}"

# Envs
joplin_role_docker_envs_default:
  TZ: "{{ tz }}"
  APP_BASE_URL: "{{ joplin_role_web_url }}"
  APP_PORT: "22300"
  POSTGRES_PASSWORD: "{{ joplin_postgres_role_docker_env_password }}"
  POSTGRES_DATABASE: "{{ joplin_postgres_role_docker_env_db }}"
  POSTGRES_USER: "{{ joplin_postgres_role_docker_env_user }}"
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "{{ joplin_postgres_name }}"
  DB_CLIENT: "pg"
joplin_role_docker_envs_custom: {}
joplin_role_docker_envs: "{{ joplin_role_docker_envs_default
                        | combine(joplin_role_docker_envs_custom) }}"

# Hostname
joplin_role_docker_hostname: "{{ joplin_name }}"

# Networks
joplin_role_docker_networks_alias: "{{ joplin_name }}"
joplin_role_docker_networks_default: []
joplin_role_docker_networks_custom: []
joplin_role_docker_networks: "{{ docker_networks_common
                            + joplin_role_docker_networks_default
                            + joplin_role_docker_networks_custom }}"

# Restart Policy
joplin_role_docker_restart_policy: unless-stopped

# State
joplin_role_docker_state: started

# Dependencies
joplin_depends_on: "{{ joplin_postgres_name }}"
joplin_depends_on_delay: "0"
joplin_depends_on_healthchecks: "false"

# Create Docker Container Timeout
joplin_docker_create_timeout: 300
