##########################################################################
# Title:            Sandbox: Koel | Default Variables                    #
# Author(s):        JigSawFr, salty                                      #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

koel_name: koel

################################
# Paths
################################

koel_role_paths_folder: "{{ koel_name }}"
koel_role_paths_location: "{{ server_appdata_path }}/{{ koel_role_paths_folder }}"
koel_role_paths_folders_list:
  - "{{ koel_role_paths_location }}"
  - "{{ koel_role_paths_location }}/app"
  - "{{ koel_role_paths_location }}/app/covers"
  - "{{ koel_role_paths_location }}/app/search-indexes"
  - "/mnt/unionfs/Media/Music"

################################
# Web
################################

koel_role_web_subdomain: "{{ koel_name }}"
koel_role_web_domain: "{{ user.domain }}"
koel_role_web_port: "80"
koel_role_web_url: "{{ 'https://' + (koel_role_web_subdomain + '.' + koel_role_web_domain
               if (koel_role_web_subdomain | length > 0)
               else koel_role_web_domain) }}"

################################
# DNS
################################

koel_role_dns_record: "{{ koel_role_web_subdomain }}"
koel_role_dns_zone: "{{ koel_role_web_domain }}"
koel_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

koel_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
koel_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
koel_role_traefik_middleware_custom: ""
koel_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
koel_role_traefik_enabled: true
koel_role_traefik_api_enabled: true
koel_role_traefik_api_endpoint: "PathPrefix(`/api`)"

################################
# Docker
################################

# Container
koel_role_docker_container: "{{ koel_name }}"

# Image
koel_role_docker_image_pull: true
koel_role_docker_image_tag: "latest"
koel_role_docker_image: "phanan/koel:{{ koel_role_docker_image_tag }}"

# Envs
koel_role_docker_envs_default:
  TZ: "{{ tz }}"
  DB_CONNECTION: "mysql"
  DB_HOST: "{{ koel_name }}-mariadb"
  DB_PORT: "3306"
  DB_DATABASE: "{{ koel_name }}"
  DB_USERNAME: "root"
  DB_PASSWORD: "{{ mariadb_role_docker_env_password }}"
  APP_KEY: "base64:{{ koel_secret_key }}"
  APP_URL: "{{ koel_role_web_url }}"
  FORCE_HTTPS: "true"
koel_role_docker_envs_custom: {}
koel_role_docker_envs: "{{ koel_role_docker_envs_default
                      | combine(koel_role_docker_envs_custom) }}"

# Volumes
koel_role_docker_volumes_default:
  - "/mnt/unionfs/Media/Music:/music:ro"
  - "{{ koel_role_paths_location }}/app/covers:/var/www/html/public/img/covers"
  - "{{ koel_role_paths_location }}/app/search-indexes:/var/www/html/storage/search-indexes"
koel_role_docker_volumes_custom: []
koel_role_docker_volumes: "{{ koel_role_docker_volumes_default
                         + koel_role_docker_volumes_custom }}"

# Hostname
koel_role_docker_hostname: "{{ koel_name }}"

# Networks
koel_role_docker_networks_alias: "{{ koel_name }}"
koel_role_docker_networks_default: []
koel_role_docker_networks_custom: []
koel_role_docker_networks: "{{ docker_networks_common
                          + koel_role_docker_networks_default
                          + koel_role_docker_networks_custom }}"

# Restart Policy
koel_role_docker_restart_policy: unless-stopped

# State
koel_role_docker_state: started

# Dependencies
koel_depends_on: "{{ koel_name }}-mariadb"
koel_depends_on_delay: "0"
koel_depends_on_healthchecks: "false"
